/*
 * This file is generated by jOOQ.
 */
package kr.co.eicn.ippbx.meta.jooq.customdb.tables.records;


import org.jooq.Record1;
import org.jooq.Table;
import org.jooq.impl.UpdatableRecordImpl;

@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class CommonMaindbMultichannelInfoRecord extends UpdatableRecordImpl<CommonMaindbMultichannelInfoRecord> {

    public CommonMaindbMultichannelInfoRecord(Table<CommonMaindbMultichannelInfoRecord> table) {
        super(table);
    }

    /**
     * Setter for <code>CUSTOMDB.maindb_multichannel_info.seq</code>.
     */
    public void setSeq(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>CUSTOMDB.maindb_multichannel_info.seq</code>.
     */
    public Integer getSeq() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>CUSTOMDB.maindb_multichannel_info.channel_type</code>.
     */
    public void setChannelType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>CUSTOMDB.maindb_multichannel_info.channel_type</code>.
     */
    public String getChannelType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>CUSTOMDB.maindb_multichannel_info.channel_data</code>.
     */
    public void setChannelData(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>CUSTOMDB.maindb_multichannel_info.channel_data</code>.
     */
    public String getChannelData() {
        return (String) get(2);
    }

    /**
     * Setter for <code>CUSTOMDB.maindb_multichannel_info.maindb_group_id</code>.
     */
    public void setMaindbGroupId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>CUSTOMDB.maindb_multichannel_info.maindb_group_id</code>.
     */
    public Integer getMaindbGroupId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>CUSTOMDB.maindb_multichannel_info.maindb_custom_id</code>.
     */
    public void setMaindbCustomId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>CUSTOMDB.maindb_multichannel_info.maindb_custom_id</code>.
     */
    public String getMaindbCustomId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>CUSTOMDB.maindb_multichannel_info.maindb_custom_name</code>.
     */
    public void setMaindbCustomName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>CUSTOMDB.maindb_multichannel_info.maindb_custom_name</code>.
     */
    public String getMaindbCustomName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>CUSTOMDB.maindb_multichannel_info.company_id</code>.
     */
    public void setCompanyId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>CUSTOMDB.maindb_multichannel_info.company_id</code>.
     */
    public String getCompanyId() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }
}
