# server config
server:
  port: 80
  servlet:
    session:
      timeout: 43200
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel.enabled: false

# definition config
eicn:
  service:
    base-url: https://dev.eicn.co.kr
    servicekind: SC
  apiserver: ${eicn.service.base-url}/api-server
  realapiserver: ${eicn.service.base-url}/api-server
  doub:
    url: ${eicn.service.base-url}
  webchat:
    image:
      url: ${eicn.service.base-url}:8200/webchat_bot_image
  callbot:
    url: ${eicn.service.base-url}:9300/callbot_conv
  file:
    location: /tmp
  chatbot:
    resource:
      location: /tmp/chatbot
  debugging: true

stt:
  transcribe:
    dbHost: 122.49.74.102

assist:
  kms:
    auth:
      # KMS 로그인 (인증)
      url: https://assistweb.uplus.co.kr:3006/api/assist/graphql
    api:
      # KMS 게시글
      url: https://assistweb.uplus.co.kr/kms/graphql
  stt:
    socket:
      # stt 소켓 연결
      url: https://assistweb.uplus.co.kr:8087
    request:
      # stt 가져오기 url
      url: https://assistweb.uplus.co.kr:8087
  sso:
    token:
      get:
        # 상담지원 버튼 클릭시, 상무님 서버로 부터 토큰을 발급 받음 (1)
        url: ${eicn.service.base-url}:8087/get_assist_token
    request:
      site:
        # 상담지원 버튼 클릭시, 독립형 어시스트 사이트를 오픈 (2)
        url: https://assistweb.uplus.co.kr/login
  login:
    record:
      # 유저 로그인시 session 기록용 url
      user: ${eicn.service.base-url}:8400/login_info