# server config
server:
  port: 8081
  servlet:
    session:
      timeout: 43200
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel.enabled: false

# definition config
eicn:
  service:
    base-url: http://localhost
    servicekind: SC
  apiserver: http://localhost:8080/api-server
  #apache 를  web 서버로 사용할 경우 아래 url 을 http://localhost:8080/api-server 로 변경 하세요.
  #이후 apache 가 접근 할 수 있도록 chown -R root:daemon /usr/local/tomcat/webapps 권한 추가 해주세요.
  realapiserver: http://localhost:8080/api-server
  #ROOT 배포시 /ubiz 삭제
  doub:
    url: http://localhost:21003/ubiz
  webchat:
    image:
      url: https://dev.eicn.co.kr:8200/webchat_bot_image
  callbot:
    url: https://dev.eicn.co.kr:9300/callbot_conv
  file:
    location: D:\temp
  chatbot:
    resource:
      location: D:\temp\chatbot
  debugging: true

atcenter:
  api:
    url: http://180.210.117.169:80
  auth:
    srvcKey: rO0ABXQAQDk3ZDNkNmQxZjhiYmUyNmI1ZjZiMDU4MWQ4NzMxZjJkMDNiYzExZGE3N2Q2Y2VlZmFkYmMzYmEzM2ZkMmMzZTc
    scrKey: wyRhma9uJfjAt408bt9UknN4ttyFwDJOWrPiGziMjk1RJSbHjLeSR8qwZp71PCge

stt:
  transcribe:
    dbHost: 122.49.74.102

assist:
  kms:
    auth:
      # KMS 로그인 (인증)
      url: https://assist.eicn.co.kr:3006/api/assist/graphql
    api:
      # KMS 게시글
      url: https://assist.eicn.co.kr/kms/graphql
  stt:
    socket:
      # stt 소켓 연결
      url: https://assist.eicn.co.kr:8087
    request:
      # stt 가져오기 url
      url: https://assist.eicn.co.kr:8087
  sso:
    token:
      get:
        # 상담지원 버튼 클릭시, 상무님 서버로 부터 토큰을 발급 받음 (1)
        url: https://dev.eicn.co.kr:8400/get_assist_token
    request:
      site:
        # 상담지원 버튼 클릭시, 독립형 어시스트 사이트를 오픈 (2)
        url: https://assist.eicn.co.kr:3006/login
  login:
    record:
      # 유저 로그인시 session 기록용 url
      user: https://dev.eicn.co.kr:8400/login_info