package kr.co.eicn.ippbx.meta.jooq.pds.tables.pojos;

import lombok.Data;

import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;

@Data
public class CommonPDSCustomInfo implements Serializable {
    private String pdsSysCustomId;
    private Timestamp pdsSysUploadDate;
    private Timestamp pdsSysUpdateDate;
    private Integer pdsSysGroupId;
    private Integer pdsSysGroupType;
    private Integer pdsSysResultType;
    private String pdsSysDamdangId;
    private String pdsSysRidNumber;
    private Integer pdsSysLastResultId;
    private Timestamp pdsSysLastResultDate;
    private Timestamp pdsSysLastCallDate;
    private String pdsSysLastHangupCause;
    private String pdsSysLastCallUniqueid;
    private String pdsSysCompanyId;
    private Date pdsDate_1;
    private Date pdsDate_2;
    private Date pdsDate_3;
    private Date pdsDay_1;
    private Date pdsDay_2;
    private Date pdsDay_3;
    private Timestamp pdsDatetime_1;
    private Timestamp pdsDatetime_2;
    private Timestamp pdsDatetime_3;
    private Integer pdsInt_1;
    private Integer pdsInt_2;
    private Integer pdsInt_3;
    private Integer pdsInt_4;
    private Integer pdsInt_5;
    private String pdsNumber_1;
    private String pdsNumber_2;
    private String pdsNumber_3;
    private String pdsNumber_4;
    private String pdsNumber_5;
    private String pdsString_1;
    private String pdsString_2;
    private String pdsString_3;
    private String pdsString_4;
    private String pdsString_5;
    private String pdsString_6;
    private String pdsString_7;
    private String pdsString_8;
    private String pdsString_9;
    private String pdsString_10;
    private String pdsString_11;
    private String pdsString_12;
    private String pdsString_13;
    private String pdsString_14;
    private String pdsString_15;
    private String pdsString_16;
    private String pdsString_17;
    private String pdsString_18;
    private String pdsString_19;
    private String pdsString_20;
    private String pdsCode_1;
    private String pdsCode_2;
    private String pdsCode_3;
    private String pdsCode_4;
    private String pdsCode_5;
    private String pdsCode_6;
    private String pdsCode_7;
    private String pdsCode_8;
    private String pdsCode_9;
    private String pdsCode_10;
    private String pdsMulticode_1;
    private String pdsMulticode_2;
    private String pdsMulticode_3;
    private String pdsConcode_1;
    private String pdsConcode_2;
    private String pdsConcode_3;
    private String pdsCscode_1;
    private String pdsCscode_2;
    private String pdsCscode_3;
}
