package kr.co.eicn.ippbx.server.jooq.customdb.tables;

import lombok.Data;

import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;

@Data
public class CommonMaindbCustomResult implements Serializable {
    private Integer seq;
    private String companyId;
    private Timestamp resultDate;
    private Timestamp updateDate;
    private String uniqueid;
    private String hangupCause;
    private String hangupMsg;
    private Integer billsec;
    private String customId;
    private String clickKey;
    private String customNumber;
    private String executeId;
    private Integer groupId;
    private String userid;
    private String useridOrg;
    private String useridTr;
    private Integer resultType;
    private String callType;
    private String fromOrg;
    private String groupKind;
    private Integer groupType;
    private Date rsDate_1;
    private Date rsDate_2;
    private Date rsDate_3;
    private Date rsDay_1;
    private Date rsDay_2;
    private Date rsDay_3;
    private Timestamp rsDatetime_1;
    private Timestamp rsDatetime_2;
    private Timestamp rsDatetime_3;
    private Integer rsInt_1;
    private Integer rsInt_2;
    private Integer rsInt_3;
    private Integer rsInt_4;
    private Integer rsInt_5;
    private String rsNumber_1;
    private String rsNumber_2;
    private String rsNumber_3;
    private String rsNumber_4;
    private String rsNumber_5;
    private String rsString_1;
    private String rsString_2;
    private String rsString_3;
    private String rsString_4;
    private String rsString_5;
    private String rsString_6;
    private String rsString_7;
    private String rsString_8;
    private String rsString_9;
    private String rsString_10;
    private String rsString_11;
    private String rsString_12;
    private String rsString_13;
    private String rsString_14;
    private String rsString_15;
    private String rsString_16;
    private String rsString_17;
    private String rsString_18;
    private String rsString_19;
    private String rsString_20;
    private String rsCode_1;
    private String rsCode_2;
    private String rsCode_3;
    private String rsCode_4;
    private String rsCode_5;
    private String rsCode_6;
    private String rsCode_7;
    private String rsCode_8;
    private String rsCode_9;
    private String rsCode_10;
    private String rsMulticode_1;
    private String rsMulticode_2;
    private String rsMulticode_3;
    private String rsConcode_1;
    private String rsConcode_2;
    private String rsConcode_3;
    private String rsCscode_1;
    private String rsCscode_2;
    private String rsCscode_3;
}
