/*
 * This file is generated by jOOQ.
 */
package kr.co.eicn.ippbx.server.jooq.customdb.tables;


import kr.co.eicn.ippbx.server.jooq.customdb.Customdb;
import kr.co.eicn.ippbx.server.jooq.customdb.Indexes;
import kr.co.eicn.ippbx.server.jooq.customdb.Keys;
import kr.co.eicn.ippbx.server.jooq.customdb.tables.records.VocResultRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

public class CommonVocResult extends TableImpl<VocResultRecord> {

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VocResultRecord> getRecordType() {
        return VocResultRecord.class;
    }

    /**
     * The column <code>CUSTOMDB.voc_result.seq</code>.
     */
    public final TableField<VocResultRecord, Integer> SEQ = createField(DSL.name("seq"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>CUSTOMDB.voc_result.result_date</code>.
     */
    public final TableField<VocResultRecord, Timestamp> RESULT_DATE = createField(DSL.name("result_date"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("2010-01-01 00:00:00", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>CUSTOMDB.voc_result.uniqueid</code>.
     */
    public final TableField<VocResultRecord, String> UNIQUEID = createField(DSL.name("uniqueid"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>CUSTOMDB.voc_result.hangup_cause</code>.
     */
    public final TableField<VocResultRecord, String> HANGUP_CAUSE = createField(DSL.name("hangup_cause"), org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>CUSTOMDB.voc_result.hangup_msg</code>.
     */
    public final TableField<VocResultRecord, String> HANGUP_MSG = createField(DSL.name("hangup_msg"), org.jooq.impl.SQLDataType.VARCHAR(100).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>CUSTOMDB.voc_result.billsec</code>.
     */
    public final TableField<VocResultRecord, Integer> BILLSEC = createField(DSL.name("billsec"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>CUSTOMDB.voc_result.custom_number</code>.
     */
    public final TableField<VocResultRecord, String> CUSTOM_NUMBER = createField(DSL.name("custom_number"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>CUSTOMDB.voc_result.userid</code>. 상담자
     */
    public final TableField<VocResultRecord, String> USERID = createField(DSL.name("userid"), org.jooq.impl.SQLDataType.VARCHAR(30).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "상담자");

    /**
     * The column <code>CUSTOMDB.voc_result.voc_group_id</code>. VOC그룹 아이디
     */
    public final TableField<VocResultRecord, Integer> VOC_GROUP_ID = createField(DSL.name("voc_group_id"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "VOC그룹 아이디");

    /**
     * The column <code>CUSTOMDB.voc_result.research_id</code>. 설문 아이디
     */
    public final TableField<VocResultRecord, Integer> RESEARCH_ID = createField(DSL.name("research_id"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "설문 아이디");

    /**
     * The column <code>CUSTOMDB.voc_result.tree_path</code>. 설문단계
     */
    public final TableField<VocResultRecord, String> TREE_PATH = createField(DSL.name("tree_path"), org.jooq.impl.SQLDataType.VARCHAR(800).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "설문단계");

    /**
     * The column <code>CUSTOMDB.voc_result.company_id</code>. 고객사 아이디
     */
    public final TableField<VocResultRecord, String> COMPANY_ID = createField(DSL.name("company_id"), org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "고객사 아이디");

    private final String tableName;

    /**
     * Create an aliased <code>CUSTOMDB.voc_result</code> table reference
     */
    public CommonVocResult(String companyName) {
        this(DSL.name("voc_result_" + companyName), null);
    }

    private CommonVocResult(String alias, Table<VocResultRecord> aliased) {
        this(DSL.name(alias), aliased);
    }

    private CommonVocResult(Name alias, Table<VocResultRecord> aliased) {
        this(alias, aliased, null);
    }

    private CommonVocResult(Name alias, Table<VocResultRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
        this.tableName = alias.last();
    }

    public <O extends Record> CommonVocResult(CommonVocResult table, Table<O> child, ForeignKey<O, VocResultRecord> key) {
        super(child, key, table);
        this.tableName = table.getName();
    }

    @Override
    public Schema getSchema() {
        return Customdb.CUSTOMDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.VOC_RESULT_PRIMARY, Indexes.VOC_RESULT_RESEARCH_ID, Indexes.VOC_RESULT_TREE_PATH);
    }

    @Override
    public Identity<VocResultRecord, Integer> getIdentity() {
        return Keys.IDENTITY_VOC_RESULT;
    }

    @Override
    public UniqueKey<VocResultRecord> getPrimaryKey() {
        return Keys.KEY_VOC_RESULT_PRIMARY;
    }

    @Override
    public List<UniqueKey<VocResultRecord>> getKeys() {
        return Arrays.<UniqueKey<VocResultRecord>>asList(Keys.KEY_VOC_RESULT_PRIMARY);
    }

    @Override
    public CommonVocResult as(String alias) {
        return new CommonVocResult(DSL.name(alias), this);
    }

    @Override
    public CommonVocResult as(Name alias) {
        return new CommonVocResult(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CommonVocResult rename(String name) {
        return new CommonVocResult(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CommonVocResult rename(Name name) {
        return new CommonVocResult(name, null);
    }

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row13<Integer, Timestamp, String, String, String, Integer, String, Integer, String, Integer, String, String, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }
}
