server:
  port: 8081
  servlet:
    session:
      timeout: 43200
spring:
  profiles:
    active: local
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  application:
    name: eicn-premium
  messages:
    basename: classpath:messages
    encoding: UTF-8
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  servlet:
    multipart:
      file-size-threshold: 1MB
      max-request-size: 100MB
      max-file-size: 100MB
logging:
  config: classpath:logback-spring.xml
management:
  metrics:
    tags:
      application: ${spring.application.name}-metrics
  endpoints:
    web:
      exposure:
        include: "health, info, prometheus"
  health:
    mail:
      enabled: false
  security:
    enabled: false
security:
  basic:
    enabled: false
# 정의 설정
eicn:
  service:
    base-url: http://localhost:21003
    servicekind: SC
  version: 20210525
  debugging: true
  swagger:
    api-package: kr.co.eicn.ippbx.front.controller.api
  file:
    location: ./files
  apiserver: http://localhost:8080/api-server
  #apache 를  web 서버로 사용할 경우 아래 url 을 http://localhost:8080/api-server 로 변경 하세요.
  #이후 apache 가 접근 할 수 있도록 chown -R root:daemon /usr/local/tomcat/webapps 권한 추가 해주세요.
  realapiserver: http://localhost:8080/api-server
  #ROOT 배포시 /ubiz 삭제
  doub:
    url: http://localhost:21003/ubiz
  webchat:
    image:
      url: https://dev.eicn.co.kr:8200/webchat_bot_image
  admin:
    socket:
      id: monitor_connector
  call-control:
    socket:
      id: maincli_connector
  talk:
    socket:
      id: talk_connector
  wtalk:
    socket:
      id: wtlk_connector
  pds:
    socket:
      id: pds_connector
  messenger:
    socket:
      id: chatting_connector
    cipher:
      key: eicn
  chatbot:
    socket:
      id: webchatcli_connector
    resource:
      location: /tmp/chatbot

