package kr.co.eicn.ippbx.server.model.dto.customdb;

import lombok.Data;

import java.sql.Date;
import java.sql.Timestamp;

@Data
public class CommonMaindbCustomInfoResponse {
    private String maindb_sys_custom_id;
    private Timestamp maindb_sys_upload_date;
    private Timestamp maindb_sys_update_date;
    private Integer maindb_sys_group_id;
    private Integer maindb_sys_group_type;
    private Integer maindb_sys_result_type;
    private String maindb_sys_damdang_id;
    private Integer maindb_sys_last_result_id;
    private Timestamp maindb_sys_last_result_date;
    private String maindb_sys_company_id;
    private Date maindb_date_1;
    private Date maindb_date_2;
    private Date maindb_date_3;
    private Date maindb_day_1;
    private Date maindb_day_2;
    private Date maindb_day_3;
    private Timestamp maindb_datetime_1;
    private Timestamp maindb_datetime_2;
    private Timestamp maindb_datetime_3;
    private Integer maindb_int_1;
    private Integer maindb_int_2;
    private Integer maindb_int_3;
    private Integer maindb_int_4;
    private Integer maindb_int_5;
    private String maindb_string_1;
    private String maindb_string_2;
    private String maindb_string_3;
    private String maindb_string_4;
    private String maindb_string_5;
    private String maindb_string_6;
    private String maindb_string_7;
    private String maindb_string_8;
    private String maindb_string_9;
    private String maindb_string_10;
    private String maindb_string_11;
    private String maindb_string_12;
    private String maindb_string_13;
    private String maindb_string_14;
    private String maindb_string_15;
    private String maindb_string_16;
    private String maindb_string_17;
    private String maindb_string_18;
    private String maindb_string_19;
    private String maindb_string_20;
    private String maindb_code_1;
    private String maindb_code_2;
    private String maindb_code_3;
    private String maindb_code_4;
    private String maindb_code_5;
    private String maindb_code_6;
    private String maindb_code_7;
    private String maindb_code_8;
    private String maindb_code_9;
    private String maindb_code_10;
    private String maindb_multicode_1;
    private String maindb_multicode_2;
    private String maindb_multicode_3;
    private String maindb_concode_1;
    private String maindb_concode_2;
    private String maindb_concode_3;
    private String maindb_cscode_1;
    private String maindb_cscode_2;
    private String maindb_cscode_3;
}
