# spring config
spring:
  profiles:
    active: ${profile}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  application:
    name: eicn-premium
  messages:
    basename: classpath:messages
    encoding: UTF-8
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  servlet:
    multipart:
      file-size-threshold: 1MB
      max-request-size: 100MB
      max-file-size: 100MB

# log config
logging:
  config: classpath:logback-spring.xml

# management config
management:
  metrics:
    tags:
      application: ${spring.application.name}-metrics
  endpoints:
    web:
      exposure:
        include: "health, info, prometheus"
  health:
    mail:
      enabled: false
  security:
    enabled: false
security:
  basic:
    enabled: false

# definition config
eicn:
  version: 20240912
  swagger:
    api-package: kr.co.eicn.ippbx.front.controller.api
  screen:
    variation: true
  admin:
    socket:
      id: monitor_connector
  call-control:
    socket:
      id: maincli_connector
  talk:
    socket:
      id: talk_connector
  wtalk:
    socket:
      id: wtlk_connector
  pds:
    socket:
      id: pds_connector
  messenger:
    socket:
      id: chatting_connector
    cipher:
      key: eicn
  chatbot:
    socket:
      id: webchatcli_connector
  message:
    url:
      id: message_connector