/*
 * This file is generated by jOOQ.
 */
package kr.co.eicn.ippbx.server.jooq.statdb.tables;

import kr.co.eicn.ippbx.server.jooq.statdb.Indexes;
import kr.co.eicn.ippbx.server.jooq.statdb.Keys;
import kr.co.eicn.ippbx.server.jooq.statdb.Statdb;
import kr.co.eicn.ippbx.server.jooq.statdb.tables.records.StatVocRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import java.sql.Date;
import java.util.Arrays;
import java.util.List;

public class CommonStatVoc extends TableImpl<StatVocRecord> {

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StatVocRecord> getRecordType() {
        return StatVocRecord.class;
    }

    /**
     * The column <code>STATDB.stat_voc.seq</code>. 고유키
     */
    public final TableField<StatVocRecord, Integer> SEQ = createField(DSL.name("seq"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "고유키");

    /**
     * The column <code>STATDB.stat_voc.company_id</code>. 회사 ID
     */
    public final TableField<StatVocRecord, String> COMPANY_ID = createField(DSL.name("company_id"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "회사 ID");

    /**
     * The column <code>STATDB.stat_voc.group_code</code>.  ex&gt;0001
     */
    public final TableField<StatVocRecord, String> GROUP_CODE = createField(DSL.name("group_code"), org.jooq.impl.SQLDataType.CHAR(4).nullable(false), this, " ex>0001");

    /**
     * The column <code>STATDB.stat_voc.group_tree_name</code>. ex&gt;0003_0008_0001
     */
    public final TableField<StatVocRecord, String> GROUP_TREE_NAME = createField(DSL.name("group_tree_name"), org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "ex>0003_0008_0001");

    /**
     * The column <code>STATDB.stat_voc.group_level</code>. 3
     */
    public final TableField<StatVocRecord, Integer> GROUP_LEVEL = createField(DSL.name("group_level"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "3");

    /**
     * The column <code>STATDB.stat_voc.voc_group_id</code>.
     */
    public final TableField<StatVocRecord, Integer> VOC_GROUP_ID = createField(DSL.name("voc_group_id"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>STATDB.stat_voc.research_id</code>. 설문아이디
     */
    public final TableField<StatVocRecord, Integer> RESEARCH_ID = createField(DSL.name("research_id"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "설문아이디");

    /**
     * The column <code>STATDB.stat_voc.userid</code>. 상담원아이디
     */
    public final TableField<StatVocRecord, String> USERID = createField(DSL.name("userid"), org.jooq.impl.SQLDataType.VARCHAR(30).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "상담원아이디");

    /**
     * The column <code>STATDB.stat_voc.research_tree_path</code>. 설문단계
     */
    public final TableField<StatVocRecord, String> RESEARCH_TREE_PATH = createField(DSL.name("research_tree_path"), org.jooq.impl.SQLDataType.VARCHAR(800).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "설문단계");

    /**
     * The column <code>STATDB.stat_voc.stat_date</code>. 생성일
     */
    public final TableField<StatVocRecord, Date> STAT_DATE = createField(DSL.name("stat_date"), org.jooq.impl.SQLDataType.DATE.nullable(false).defaultValue(org.jooq.impl.DSL.inline("2009-01-01", org.jooq.impl.SQLDataType.DATE)), this, "생성일");

    /**
     * The column <code>STATDB.stat_voc.stat_hour</code>. 생성시간
     */
    public final TableField<StatVocRecord, Byte> STAT_HOUR = createField(DSL.name("stat_hour"), org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "생성시간");

    /**
     * The column <code>STATDB.stat_voc.total</code>. 총계
     */
    public final TableField<StatVocRecord, Integer> TOTAL = createField(DSL.name("total"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "총계");

    private final String tableName;

    /**
     * Create an aliased <code>eicn.stat_voc</code> table reference
     */
    public CommonStatVoc(String companyGroup) {
        this(DSL.name("stat_voc_" + companyGroup), null);
    }

    private CommonStatVoc(String alias, Table<StatVocRecord> aliased) {
    	this(DSL.name(alias), aliased);
    }

    private CommonStatVoc(Name alias, Table<StatVocRecord> aliased) {
        this(alias, aliased, null);
    }

    private CommonStatVoc(Name alias, Table<StatVocRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
        this.tableName = alias.last();
    }

    public <O extends Record> CommonStatVoc(CommonStatVoc table, Table<O> child, ForeignKey<O, StatVocRecord> key) {
        super(child, key, table);
        this.tableName = table.getName();
    }

    @Override
    public Schema getSchema() {
        return Statdb.STATDB;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.STAT_VOC_COMPANY_ID, Indexes.STAT_VOC_PRIMARY, Indexes.STAT_VOC_RESEARCH_ID, Indexes.STAT_VOC_RESEARCH_TREE_PATH, Indexes.STAT_VOC_STAT_DATE, Indexes.STAT_VOC_STAT_HOUR, Indexes.STAT_VOC_USERID, Indexes.STAT_VOC_RESEARCH_ID);
    }

    @Override
    public Identity<StatVocRecord, Integer> getIdentity() {
        return Keys.IDENTITY_STAT_VOC;
    }

    @Override
    public UniqueKey<StatVocRecord> getPrimaryKey() {
        return Keys.KEY_STAT_VOC_PRIMARY;
    }

    @Override
    public List<UniqueKey<StatVocRecord>> getKeys() {
        return Arrays.<UniqueKey<StatVocRecord>>asList(Keys.KEY_STAT_VOC_PRIMARY);
    }

    @Override
    public CommonStatVoc as(String alias) {
        return new CommonStatVoc(DSL.name(alias), this);
    }

    @Override
    public CommonStatVoc as(Name alias) {
        return new CommonStatVoc(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CommonStatVoc rename(String name) {
        return new CommonStatVoc(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CommonStatVoc rename(Name name) {
        return new CommonStatVoc(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, Date, Byte, String, String, Integer, Integer, String, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
