package kr.co.eicn.ippbx.meta.jooq.customdb.tables.pojos;

import lombok.Data;

import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;

@Data
public class CommonPrvCustomInfo implements Serializable {
    private String    prvSysCustomId;
    private Timestamp prvSysUploadDate;
    private Timestamp prvSysUpdateDate;
    private Integer   prvSysGroupId;
    private Integer   prvSysGroupType;
    private Integer   prvSysResultType;
    private String    prvSysDamdangId;
    private String    prvSysRidNumber;
    private Integer   prvSysLastResultId;
    private Timestamp prvSysLastResultDate;
    private Timestamp prvSysLastCallDate;
    private String    prvSysLastHangupCause;
    private String    prvSysLastCallUniqueid;
    private String    prvSysCompanyId;
    private Date      prvDate_1;
    private Date      prvDate_2;
    private Date      prvDate_3;
    private Date      prvDay_1;
    private Date      prvDay_2;
    private Date      prvDay_3;
    private Timestamp prvDatetime_1;
    private Timestamp prvDatetime_2;
    private Timestamp prvDatetime_3;
    private Integer   prvInt_1;
    private Integer   prvInt_2;
    private Integer   prvInt_3;
    private Integer   prvInt_4;
    private Integer   prvInt_5;
    private String    prvNumber_1;
    private String    prvNumber_2;
    private String    prvNumber_3;
    private String    prvNumber_4;
    private String    prvNumber_5;
    private String    prvString_1;
    private String    prvString_2;
    private String    prvString_3;
    private String    prvString_4;
    private String    prvString_5;
    private String    prvString_6;
    private String    prvString_7;
    private String    prvString_8;
    private String    prvString_9;
    private String    prvString_10;
    private String    prvString_11;
    private String    prvString_12;
    private String    prvString_13;
    private String    prvString_14;
    private String    prvString_15;
    private String    prvString_16;
    private String    prvString_17;
    private String    prvString_18;
    private String    prvString_19;
    private String    prvString_20;
    private String    prvCode_1;
    private String    prvCode_2;
    private String    prvCode_3;
    private String    prvCode_4;
    private String    prvCode_5;
    private String    prvCode_6;
    private String    prvCode_7;
    private String    prvCode_8;
    private String    prvCode_9;
    private String    prvCode_10;
    private String    prvMulticode_1;
    private String    prvMulticode_2;
    private String    prvMulticode_3;
    private String    prvConcode_1;
    private String    prvConcode_2;
    private String    prvConcode_3;
    private String    prvCscode_1;
    private String    prvCscode_2;
    private String    prvCscode_3;
}
