# server config
server:
  schema: http
  host: localhost
  port: 8080

# jdbc config
jdbc:
  host: localhost
  port: 3306
  dialect: mysql
  username: eicn
  password: eicnrw
  driver-class-name: com.mysql.jdbc.Driver
  options: useUnicode=yes&characterEncoding=utf8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Seoul

# hikaricp config
hikari:
  eicn:
    maximum-pool-size: 0
  customdb:
    maximum-pool-size: 0
  configdb:
    maximum-pool-size: 0
  statdb:
    maximum-pool-size: 0
  pds:
    maximum-pool-size: 0
  max-lifetime: 3600000
  connection-timeout: 5000

# datasource config
spring:
  datasource:
    hikari:
      eicn:
        driver-class-name: ${jdbc.driver-class-name}
        jdbc-url: jdbc:${jdbc.dialect}://${jdbc.host}:${jdbc.port}/eicn?${jdbc.options}
        username: ${jdbc.username}
        password: ${jdbc.password}
        max-lifetime: ${hikari.max-lifetime}
        connection-timeout: ${hikari.connection-timeout}
      customdb:
        driver-class-name: ${jdbc.driver-class-name}
        jdbc-url: jdbc:${jdbc.dialect}://${jdbc.host}:${jdbc.port}/CUSTOMDB?${jdbc.options}
        username: ${jdbc.username}
        password: ${jdbc.password}
        max-lifetime: ${hikari.max-lifetime}
        connection-timeout: ${hikari.connection-timeout}
      configdb:
        driver-class-name: ${jdbc.driver-class-name}
        jdbc-url: jdbc:${jdbc.dialect}://${jdbc.host}:${jdbc.port}/CONFIGDB?${jdbc.options}
        username: ${jdbc.username}
        password: ${jdbc.password}
        max-lifetime: ${hikari.max-lifetime}
        connection-timeout: ${hikari.connection-timeout}
      statdb:
        driver-class-name: ${jdbc.driver-class-name}
        jdbc-url: jdbc:${jdbc.dialect}://${jdbc.host}:${jdbc.port}/STATDB?${jdbc.options}
        username: ${jdbc.username}
        password: ${jdbc.password}
        max-lifetime: ${hikari.max-lifetime}
        connection-timeout: ${hikari.connection-timeout}
      pds:
        driver-class-name: ${jdbc.driver-class-name}
        jdbc-url: jdbc:${jdbc.dialect}://${jdbc.host}:${jdbc.port}/PDS?${jdbc.options}
        username: ${jdbc.username}
        password: ${jdbc.password}
        max-lifetime: ${hikari.max-lifetime}
        connection-timeout: ${hikari.connection-timeout}
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always
      platform: mysql

# file path config
file:
  path:
    data: D:\uploads\data
    asterisk: D:\uploads\asterisk
    tts: D:\uploads\{0}\tts_temp
    stt: D:\uploads\{0}\stt\transcribe\write\{0}\{1}
    send: D:\uploads\data
    notice: ${file.path.data}\{0}\notice\{1}
    task_script: ${file.path.data}\{0}\task_script\{1}
    manual: ${file.path.data}\{0}\manual\{1}
    upload: D:\uploads\data
    chatt: ${file.path.data}\CHATT\{0}\{1}\{2}
    moh: ${file.path.asterisk}\moh
    ars: ${file.path.asterisk}\sounds\ars
    record-multi-down: ${file.path.data}\{0}\DOWNDIR
    conf-minutes-save: D:\primium_ipcc\minutes\{0}
    talk: ${file.path.data}\TALK\{0}
    custom: ${file.path.data}\{0}\CUSTOM_DATA
    profile: ${file.path.data}\{0}\PROFILE_PHOTO
    chatbot: ${file.path.data}\{0}\CHATBOT
    temporary:
      default: D:\temp
      enc: ${file.path.temporary.default}\monit\tmp_enc_{0}

# spring security config
jwt:
  secret: ippbx@IX

# etc config
env:
  rest-doc:
    port: 8080
  enc:
    master-key: MasterKey@EicnRecordEncryption

# ipcc config
ipcc:
  url: http://122.49.74.241/ipcc/cc/remote
  websocket:
    protocol: http
    ip: 122.49.74.241
    port: 8087