# spring config
spring:
  profiles:
    active: ${profile}
  messages:
    cache-duration: 3600000
    basename: i18n/message
    encoding: utf-8
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  task:
    scheduling:
      pool:
        size: 8
      thread-name-prefix: eicn-scheduler
  web:
    resources:
      cache:
        period: 31536000
        cachecontrol:
          max-age: 31536000

# server config
server:
  servlet:
    context-path: /api-server
    encoding:
      force: true
      enabled: true
      charset: UTF-8
      force-response: true
  error:
    path: /error

# mybatis config
mybatis:
  mapper-locations: classpath*:/mappers/*.xml
  type-aliases-package: kr.co.eicn.ippbx.server.model

# log config
logging:
  config: classpath:logback-spring.xml

# springdoc config
springdoc:
  show-login-endpoint: true
  swagger-ui:
    use-root-path: true
    operationsSorter: alpha
    tagsSorter: alpha
    showExtensions: true