server:
  schema: http
  host: 122.49.74.102
  port: 8080
  servlet:
    context-path: /api-server
    encoding:
      force: true
      enabled: true
      charset: utf-8
      force-response: true
  error:
    path: /error
---
# datasource config
jdbc:
  host: 122.49.74.102
  port: 3306
  dialect: mysql
  username: eicn
  password: eicnrw
  driver-class-name: com.mysql.jdbc.Driver
  options: useUnicode=yes&characterEncoding=utf8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Seoul

# hikaricp config
hikari:
  eicn:
    maximum-pool-size: 300
  customdb:
    maximum-pool-size: 200
  configdb:
    maximum-pool-size: 100
  statdb:
    maximum-pool-size: 200
  pds:
    maximum-pool-size: 100
  max-lifetime: 3600000
  connection-timeout: 5000

---
# ipcc config
ipcc:
  url: http://122.49.74.241/ipcc/cc/remote
  websocket:
    protocol: http
    ip: 122.49.74.241
    port: 8087

---
# spring config
spring:
  profiles:
    active: local
  messages:
    cache-duration: 3600000
    basename: i18n/message
    encoding: utf-8
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  task:
    scheduling:
      pool:
        size: 8
      thread-name-prefix: eicn-scheduler
  web:
    resources:
      cache:
        period: 31536000
        cachecontrol:
          max-age: 31536000
---
# file path config
file:
  path:
    data: /data
    asterisk: /var/lib/asterisk
    tts: ${file.path.data}/{0}/tts_temp
    stt: /stt/transcribe/write/{0}/{1}
    send: /data
    upload: /data
    notice: ${file.path.data}/{0}/notice/{1}
    task_script: ${file.path.data}/{0}/task_script/{1}
    manual: ${file.path.data}/{0}/manual/{1}
    chatt: ${file.path.data}/CHATT/{0}/{1}/{2}
    moh: ${file.path.asterisk}/moh
    ars: ${file.path.asterisk}/sounds/ars
    record-multi-down: ${file.path.data}/{0}/DOWNDIR
    conf-minutes-save: /var/log/eicn_log/CONF/{0}
    talk: ${file.path.data}/TALK/{0}
    custom: ${file.path.data}/{0}/CUSTOM_DATA
    profile: ${file.path.data}/{0}/PROFILE_PHOTO
    chatbot: ${file.path.data}/{0}/CHATBOT
    temporary:
      default: /tmp
      enc: ${file.path.temporary.default}/monit/tmp_enc_{0}
---
# local
spring:
  datasource:
    hikari:
      eicn:
        driver-class-name: ${jdbc.driver-class-name}
        jdbc-url: jdbc:${jdbc.dialect}://${jdbc.host}:${jdbc.port}/eicn?${jdbc.options}
        username: ${jdbc.username}
        password: ${jdbc.password}
        max-lifetime: ${hikari.max-lifetime}
        connection-timeout: ${hikari.connection-timeout}
      customdb:
        driver-class-name: ${jdbc.driver-class-name}
        jdbc-url: jdbc:${jdbc.dialect}://${jdbc.host}:${jdbc.port}/CUSTOMDB?${jdbc.options}
        username: ${jdbc.username}
        password: ${jdbc.password}
        max-lifetime: ${hikari.max-lifetime}
        connection-timeout: ${hikari.connection-timeout}
      configdb:
        driver-class-name: ${jdbc.driver-class-name}
        jdbc-url: jdbc:${jdbc.dialect}://${jdbc.host}:${jdbc.port}/CONFIGDB?${jdbc.options}
        username: ${jdbc.username}
        password: ${jdbc.password}
        max-lifetime: ${hikari.max-lifetime}
        connection-timeout: ${hikari.connection-timeout}
      statdb:
        driver-class-name: ${jdbc.driver-class-name}
        jdbc-url: jdbc:${jdbc.dialect}://${jdbc.host}:${jdbc.port}/STATDB?${jdbc.options}
        username: ${jdbc.username}
        password: ${jdbc.password}
        max-lifetime: ${hikari.max-lifetime}
        connection-timeout: ${hikari.connection-timeout}
      pds:
        driver-class-name: ${jdbc.driver-class-name}
        jdbc-url: jdbc:${jdbc.dialect}://${jdbc.host}:${jdbc.port}/PDS?${jdbc.options}
        username: ${jdbc.username}
        password: ${jdbc.password}
        max-lifetime: ${hikari.max-lifetime}
        connection-timeout: ${hikari.connection-timeout}
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always
      platform: mysql
logging:
  config: classpath:logback-spring.xml

file:
  path:
    data: D:\uploads\data
    asterisk: D:\uploads\asterisk
    tts: D:\uploads\{0}\tts_temp
    send: D:\uploads\data
    notice: ${file.path.data}\{0}\notice\{1}
    task_script: ${file.path.data}\{0}\task_script\{1}
    manual: ${file.path.data}\{0}\manual\{1}
    upload: D:\uploads\help
    chatt: ${file.path.data}\CHATT\{0}\{1}\{2}
    moh: ${file.path.asterisk}\moh
    ars: ${file.path.asterisk}\sounds\ars
    record-multi-down: ${file.path.data}\{0}\DOWNDIR
    conf-minutes-save: D:\primium_ipcc\minutes\{0}
    talk: ${file.path.data}\TALK\{0}
    custom: ${file.path.data}\{0}\CUSTOM_DATA
    profile: ${file.path.data}\{0}\PROFILE_PHOTO
    chatbot: ${file.path.data}\{0}\CHATBOT
    temporary:
      default: D:\temp
      enc: ${file.path.temporary.default}\tmp_enc_{0}

assist:
  kms:
    auth:
      # KMS 로그인 (인증)
      url: https://assist.eicn.co.kr:3006/api/assist/graphql
    api:
      # KMS 게시글
      url: https://assist.eicn.co.kr/kms/graphql
  stt:
    socket:
      # stt 소켓 연결
      url: https://assist.eicn.co.kr:8087
    request:
      # stt 가져오기 url
      url: https://assist.eicn.co.kr:8087
  sso:
    token:
      get:
        # 상담지원 버튼 클릭시, 상무님 서버로 부터 토큰을 발급 받음 (1)
        url: https://dev.eicn.co.kr:8400/get_assist_token
    request:
      site:
        # 상담지원 버튼 클릭시, 독립형 어시스트 사이트를 오픈 (2)
        url: https://assist.eicn.co.kr:3006/login
  login:
    record:
      # 유저 로그인시 session 기록용 url
      user: https://dev.eicn.co.kr:8400/login_info
---
# 개발환경
spring:
  datasource:
    hikari:
      eicn:
        driver-class-name: ${jdbc.driver-class-name}
        jdbc-url: jdbc:${jdbc.dialect}://${jdbc.host}:${jdbc.port}/eicn?${jdbc.options}
        username: ${jdbc.username}
        password: ${jdbc.password}
      customdb:
        driver-class-name: ${jdbc.driver-class-name}
        jdbc-url: jdbc:${jdbc.dialect}://${jdbc.host}:${jdbc.port}/CUSTOMDB?${jdbc.options}
        username: ${jdbc.username}
        password: ${jdbc.password}
      configdb:
        driver-class-name: ${jdbc.driver-class-name}
        jdbc-url: jdbc:${jdbc.dialect}://${jdbc.host}:${jdbc.port}/CONFIGDB?${jdbc.options}
        username: ${jdbc.username}
        password: ${jdbc.password}
      statdb:
        driver-class-name: ${jdbc.driver-class-name}
        jdbc-url: jdbc:${jdbc.dialect}://${jdbc.host}:${jdbc.port}/STATDB?${jdbc.options}
        username: ${jdbc.username}
        password: ${jdbc.password}
      pds:
        driver-class-name: ${jdbc.driver-class-name}
        jdbc-url: jdbc:${jdbc.dialect}://${jdbc.host}:${jdbc.port}/PDS?${jdbc.options}
        username: ${jdbc.username}
        password: ${jdbc.password}
  config:
    activate:
      on-profile: dev
  sql:
    init:
      mode: always
      platform: mysql
logging:
  config: classpath:logback-spring.xml

assist:
  kms:
    auth:
      # KMS 로그인 (인증)
      url: https://assist.eicn.co.kr:3006/api/assist/graphql
    api:
      # KMS 게시글
      url: https://assist.eicn.co.kr/kms/graphql
  stt:
    socket:
      # stt 소켓 연결
      url: https://assist.eicn.co.kr:8087
    request:
      # stt 가져오기 url
      url: https://assist.eicn.co.kr:8087
  sso:
    token:
      get:
        # 상담지원 버튼 클릭시, 상무님 서버로 부터 토큰을 발급 받음 (1)
        url: https://dev.eicn.co.kr:8400/get_assist_token
    request:
      site:
        # 상담지원 버튼 클릭시, 독립형 어시스트 사이트를 오픈 (2)
        url: https://assist.eicn.co.kr:3006/login
  login:
    record:
      # 유저 로그인시 session 기록용 url
      user: https://dev.eicn.co.kr:8400/login_info
---
# 운영
server:
  host: 122.49.74.102

jdbc:
  host: 122.49.74.102

spring:
  datasource:
    hikari:
      eicn:
        driver-class-name: ${jdbc.driver-class-name}
        jdbc-url: jdbc:${jdbc.dialect}://${jdbc.host}:${jdbc.port}/eicn?${jdbc.options}
        username: ${jdbc.username}
        password: ${jdbc.password}
        maximum-pool-size: ${hikari.eicn.maximum-pool-size}
        max-lifetime: ${hikari.max-lifetime}
        connection-timeout: ${hikari.connection-timeout}
      customdb:
        driver-class-name: ${jdbc.driver-class-name}
        jdbc-url: jdbc:${jdbc.dialect}://${jdbc.host}:${jdbc.port}/CUSTOMDB?${jdbc.options}
        username: ${jdbc.username}
        password: ${jdbc.password}
        maximum-pool-size: ${hikari.customdb.maximum-pool-size}
        max-lifetime: ${hikari.max-lifetime}
        connection-timeout: ${hikari.connection-timeout}
      configdb:
        driver-class-name: ${jdbc.driver-class-name}
        jdbc-url: jdbc:${jdbc.dialect}://${jdbc.host}:${jdbc.port}/CONFIGDB?${jdbc.options}
        username: ${jdbc.username}
        password: ${jdbc.password}
        maximum-pool-size: ${hikari.configdb.maximum-pool-size}
        max-lifetime: ${hikari.max-lifetime}
        connection-timeout: ${hikari.connection-timeout}
      statdb:
        driver-class-name: ${jdbc.driver-class-name}
        jdbc-url: jdbc:${jdbc.dialect}://${jdbc.host}:${jdbc.port}/STATDB?${jdbc.options}
        username: ${jdbc.username}
        password: ${jdbc.password}
        maximum-pool-size: ${hikari.statdb.maximum-pool-size}
        max-lifetime: ${hikari.max-lifetime}
        connection-timeout: ${hikari.connection-timeout}
      pds:
        driver-class-name: ${jdbc.driver-class-name}
        jdbc-url: jdbc:${jdbc.dialect}://${jdbc.host}:${jdbc.port}/PDS?${jdbc.options}
        username: ${jdbc.username}
        password: ${jdbc.password}
        maximum-pool-size: ${hikari.pds.maximum-pool-size}
        max-lifetime: ${hikari.max-lifetime}
        connection-timeout: ${hikari.connection-timeout}
  config:
    activate:
      on-profile: stage
  sql:
    init:
      mode: always
      platform: mysql
logging:
  config: classpath:logback-spring.xml
---
# mybatis
mybatis:
  mapper-locations: classpath*:/mappers/*.xml
  type-aliases-package: kr.co.eicn.ippbx.server.model
---
# spring security config
jwt:
  secret: ippbx@IX
---
# 기타 환경설정
env:
  rest-doc:
    port: 8080
  enc:
    master-key: MasterKey@EicnRecordEncryption

---
