-- DEFAULT 스키마 설정

#################    CUSTOMDB    #################
CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`chatt_bookmark`
(
    `seq`      INT     NOT NULL AUTO_INCREMENT,
    `userid`   VARCHAR(50) NULL DEFAULT '',
    `memberid` VARCHAR(50) NULL DEFAULT '',
    UNIQUE INDEX `seq` (`seq`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`chatt_msg`
(
    `seq`          INT       NOT NULL AUTO_INCREMENT,
    `room_id`      VARCHAR(50)   NULL     DEFAULT '',
    `userid`       VARCHAR(30)   NULL     DEFAULT '',
    `insert_time`  DATETIME      NOT NULL DEFAULT '2009-07-01 00:00:00',
    `send_receive` CHAR(3)       NULL     DEFAULT '',
    `message_id`   VARCHAR(100)  NULL     DEFAULT '',
    `type`         VARCHAR(10)   NOT NULL DEFAULT '',
    `content`      VARCHAR(1100) NOT NULL DEFAULT '',
    UNIQUE INDEX `seq` (`seq`) USING BTREE,
    INDEX `room_id` (`room_id`) USING BTREE,
    INDEX `insert_time` (`insert_time`) USING BTREE,
    INDEX `userid` (`userid`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`chatt_msg_read`
(
    `message_id` VARCHAR(100) NOT NULL DEFAULT '',
    `room_id`    VARCHAR(50)  NULL     DEFAULT '',
    `userid`     VARCHAR(30)  NULL     DEFAULT '',
    INDEX `message_id` (`message_id`) USING BTREE,
    INDEX `room_id` (`room_id`) USING BTREE,
    INDEX `userid` (`userid`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`chatt_room`
(
    `room_id`               VARCHAR(50)  NOT NULL,
    `room_name`             VARCHAR(100) NULL     DEFAULT '',
    `room_name_change`      CHAR(1)      NULL     DEFAULT '',
    `member_md5`            VARCHAR(50)  NULL     DEFAULT '',
    `start_time`            DATETIME     NULL     DEFAULT '2009-07-01 00:00:00',
    `last_time`             DATETIME     NULL     DEFAULT '2009-07-01 00:00:00',
    `last_msg`              VARCHAR(500) NULL     DEFAULT '',
    `last_msg_type`         VARCHAR(10)  NULL     DEFAULT '',
    `last_msg_send_receive` CHAR(3)      NULL     DEFAULT '',
    `last_userid`           VARCHAR(30)  NULL     DEFAULT '',
    `make_userid`           VARCHAR(30)  NULL     DEFAULT '',
    `cur_member_cnt`        INT      NOT NULL DEFAULT '0',
    `org_member_cnt`        INT      NOT NULL DEFAULT '0',
    PRIMARY KEY (`room_id`) USING BTREE,
    INDEX `member_md5` (`member_md5`) USING BTREE,
    INDEX `last_time` (`last_time`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`chatt_room_member`
(
    `room_id`     VARCHAR(50)  NOT NULL,
    `userid`      VARCHAR(30)  NOT NULL,
    `room_name`   VARCHAR(100) NULL DEFAULT '',
    `member_md5`  VARCHAR(50)  NULL DEFAULT '',
    `is_join`     CHAR(1)      NULL DEFAULT '',
    `invite_time` DATETIME     NULL DEFAULT '2019-04-01 00:00:00',
    `last_msg`    VARCHAR(500) NULL DEFAULT '',
    `last_type`   VARCHAR(10)  NULL DEFAULT '',
    `last_time`   DATETIME     NULL DEFAULT '2019-04-01 00:00:00',
    `read_time`   DATETIME     NULL DEFAULT '2019-04-01 00:00:00',
    PRIMARY KEY (`room_id`, `userid`) USING BTREE,
    INDEX `room_id` (`room_id`) USING BTREE,
    INDEX `userid` (`userid`) USING BTREE,
    INDEX `member_md5` (`member_md5`) USING BTREE,
    INDEX `last_time` (`last_time`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`eicn_cdr`
(
    `seq`                INT      NOT NULL AUTO_INCREMENT,
    `ring_date`          DATETIME     NULL DEFAULT '2010-01-01 01:00:00' COMMENT '전화수발신시간',
    `waiting_date`       DATETIME     NULL DEFAULT '2010-01-01 01:00:00' COMMENT '헌트에들어와서기다리기시작한시간',
    `dialup_date`        DATETIME     NULL DEFAULT '2010-01-01 01:00:00' COMMENT '상대방이전화를받은시간',
    `hangup_date`        DATETIME     NULL DEFAULT '2010-01-01 01:00:00' COMMENT '전화가종료된시간',
    `duration`           INT      NULL DEFAULT '0' COMMENT 'hangup_date-ring_date',
    `billsec`            INT      NULL DEFAULT '0' COMMENT 'hangup_date-dialup_date',
    `waitsec`            INT      NULL DEFAULT '0' COMMENT 'waiting_date-dialup_date',
    `in_out`             CHAR(1)      NULL DEFAULT 'I' COMMENT '수신/발신여부',
    `dcontext`           VARCHAR(20)  NULL DEFAULT '' COMMENT '다이얼플랜에서의컨텍스트',
    `peer`               VARCHAR(30)  NULL DEFAULT '' COMMENT '전화기아이디',
    `src`                VARCHAR(30)  NULL DEFAULT '' COMMENT '수신내선또는수신고객번호',
    `dst`                VARCHAR(30)  NULL DEFAULT '' COMMENT '발신내선또는발신고객번호',
    `callstatus`         CHAR(1)      NULL DEFAULT 'R' COMMENT '전화상태 C-클릭투콜 R-링이가는중 D-전화받음 H-전화끊음',
    `detail_callstatus`  VARCHAR(500) NULL DEFAULT '' COMMENT '다이얼플랜상디테일콜상태또는단계',
    `record_info`        VARCHAR(20)  NULL DEFAULT '' COMMENT '녹취 S-녹취없음 M-녹취됨 M_$순차 -부분녹취가 발생하여 녹취가 여려개임',
    `record_file`        VARCHAR(300) NULL DEFAULT '' COMMENT '녹취파일경로',
    `uniqueid`           VARCHAR(50)  NULL DEFAULT '' COMMENT '아스터리스크 발신쪽 콜유니크 아이디 돌려줬을경우 같을수도 있음',
    `dst_uniqueid`       VARCHAR(50)  NULL DEFAULT '' COMMENT '아스터리스크 수신쪽 콜유니크',
    `channel`            VARCHAR(200) NULL DEFAULT '' COMMENT '아스터리스크 발신쪽 채널아이디',
    `dst_channel`        VARCHAR(200) NULL DEFAULT '' COMMENT '아스터리스크 수신쪽 채널아이디',
    `ini_num`            VARCHAR(50)  NULL DEFAULT '' COMMENT '인바운드-첫인입대표 아웃바운드-발신CID',
    `second_num`         VARCHAR(50)  NULL DEFAULT '' COMMENT '인바운드에서는헌트번호 아웃바운드에서는 발신과금번호',
    `worktime_yn`        CHAR(1)      NULL DEFAULT 'Y' COMMENT '업무시간여부',
    `stat_yn`            CHAR(1)      NULL DEFAULT 'Y' COMMENT '통계쌓을지여부',
    `ivr_key`            VARCHAR(300) NULL DEFAULT '' COMMENT '인바운드에서 IVR순서',
    `queue_strategy`     VARCHAR(30)  NULL DEFAULT '' COMMENT '헌트의 콜분배 STRATEGY',
    `queue_sequence`     VARCHAR(500) NULL DEFAULT '' COMMENT '헌트의 콜분배순서 전화기아이디',
    `callee_hangup`      CHAR(1)      NULL DEFAULT '' COMMENT 'Y-받은사람이먼저끊음 N-건사람이 먼저끊음',
    `web_voice_info`     VARCHAR(50)  NULL DEFAULT '' COMMENT '보이는ARS사용여부',
    `vip_black`          CHAR(1)      NULL DEFAULT '' COMMENT 'VIP-V,BLACK-B',
    `userid`             VARCHAR(50)  NULL DEFAULT '' COMMENT '전화기사용자아이디',
    `group_code`         CHAR(4)      NULL DEFAULT '' COMMENT '전화기사용자소속코드',
    `group_tree_name`    VARCHAR(50)  NULL DEFAULT '' COMMENT '전화기사용자소속트리명',
    `group_level`        INT      NULL DEFAULT '0' COMMENT '전화기사용자소속트리레벨',
    `company_id`         VARCHAR(30)  NULL DEFAULT '' COMMENT '컴퍼니아이디',
    `host`               VARCHAR(20)  NULL DEFAULT '' COMMENT '콜이진행된PBX_SERVER',
    `hangup_cause`       VARCHAR(100) NULL DEFAULT '' COMMENT '전화가끊어진원인',
    `cmp_click_key`      VARCHAR(100) NULL DEFAULT '' COMMENT '전화돌려주기,당겨받기 순서',
    `cmp_click_from`     VARCHAR(20)  NULL DEFAULT '' COMMENT '콜을시도한성격 PDS,PRV,MAINDB등등',
    `cmp_group_id`       INT      NULL DEFAULT '0' COMMENT '캠페인그룹',
    `cmp_customid`       VARCHAR(100) NULL DEFAULT '' COMMENT '캠페인고객아이디',
    `turn_over_cnt`      INT      NULL DEFAULT '0' COMMENT '전화돌려주기,당겨받기 순서',
    `turn_over_kind`     VARCHAR(30)  NULL DEFAULT '' COMMENT '전화돌려주기,당겨받기 종류',
    `turn_over_number`   VARCHAR(50)  NULL DEFAULT '' COMMENT '전화돌려주기,당겨받기 번호',
    `turn_over_uniqueid` VARCHAR(50)  NULL DEFAULT '' COMMENT '전화돌려주기,당겨받기 uniqueid',
    `etc1`               VARCHAR(100) NULL DEFAULT '',
    `etc2`               VARCHAR(100) NULL DEFAULT '',
    `etc3`               VARCHAR(100) NULL DEFAULT '',
    `etc4`               VARCHAR(100) NULL DEFAULT '',
    `etc5`               VARCHAR(100) NULL DEFAULT '',
    PRIMARY KEY (`seq`) USING BTREE,
    INDEX `ring_date` (`ring_date`) USING BTREE,
    INDEX `dst` (`dst`) USING BTREE,
    INDEX `src` (`src`) USING BTREE,
    INDEX `billsec` (`billsec`) USING BTREE,
    INDEX `userid` (`userid`) USING BTREE,
    INDEX `uniqueid` (`uniqueid`) USING BTREE,
    INDEX `dst_uniqueid` (`dst_uniqueid`) USING BTREE,
    INDEX `callstatus` (`callstatus`) USING BTREE,
    INDEX `company_id` (`company_id`) USING BTREE,
    INDEX `turn_over_number` (`turn_over_number`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`kakao_chatbot_block`
(
    `seq`                  INT      NOT NULL AUTO_INCREMENT,
    `bot_id`               VARCHAR(50)  NOT NULL,
    `bot_name`             VARCHAR(50)  NULL DEFAULT '',
    `block_id`             VARCHAR(50)  NULL DEFAULT '',
    `block_name`           VARCHAR(50)  NULL DEFAULT '',
    `response_type`        VARCHAR(30)  NULL DEFAULT '',
    `response_get_url`     VARCHAR(100) NULL DEFAULT '',
    `response_param_names` VARCHAR(100) NULL DEFAULT '',
    `event_name`           VARCHAR(50)  NULL DEFAULT '',
    `use_yn`               CHAR(1)      NULL DEFAULT '',
    UNIQUE INDEX `seq` (`seq`) USING BTREE,
    INDEX `bot_id` (`bot_id`) USING BTREE,
    INDEX `block_id` (`block_id`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`kakao_event`
(
    `seq`                 INT      NOT NULL AUTO_INCREMENT,
    `insert_date`         DATETIME     NULL DEFAULT '2021-01-01 00:00:00',
    `update_date`         DATETIME     NULL DEFAULT '2021-01-01 00:00:00',
    `bot_id`              VARCHAR(50)  NOT NULL,
    `bot_name`            VARCHAR(100) NULL DEFAULT '',
    `event_name`          VARCHAR(50)  NULL DEFAULT '',
    `user_type`           VARCHAR(50)  NULL DEFAULT '',
    `user_id`             VARCHAR(100) NULL DEFAULT '',
    `user_name`           VARCHAR(50)  NULL DEFAULT '',
    `user_data`           VARCHAR(500) NULL DEFAULT '',
    `task_id`             VARCHAR(100) NULL DEFAULT '',
    `response_block_id`   VARCHAR(50)  NULL DEFAULT '',
    `response_block_name` VARCHAR(50)  NULL DEFAULT '',
    UNIQUE INDEX `seq` (`seq`) USING BTREE,
    INDEX `insert_date` (`insert_date`) USING BTREE,
    INDEX `bot_id` (`bot_id`) USING BTREE,
    INDEX `user_id` (`user_id`) USING BTREE,
    INDEX `response_block_id` (`response_block_id`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`kakao_profile`
(
    `seq`                             INT      NOT NULL AUTO_INCREMENT,
    `insert_date`                     DATETIME     NULL DEFAULT '2021-01-01 00:00:00',
    `update_date`                     DATETIME     NULL DEFAULT '2021-01-01 00:00:00',
    `bot_id`                          VARCHAR(50)  NOT NULL,
    `request_user_id`                 VARCHAR(100) NULL DEFAULT '',
    `request_user_plusfriend_userkey` VARCHAR(50)  NULL DEFAULT '',
    `nickname`                        VARCHAR(50)  NULL DEFAULT '',
    `profile_image_url`               VARCHAR(100) NULL DEFAULT '',
    `phone_number`                    VARCHAR(30)  NULL DEFAULT '',
    `email`                           VARCHAR(50)  NULL DEFAULT '',
    `app_user_id`                     VARCHAR(50)  NULL DEFAULT '',
    `maindb_group_id`                 INT      NULL DEFAULT '0',
    `maindb_custom_id`                VARCHAR(100) NULL DEFAULT '',
    `maindb_custom_name`              VARCHAR(100) NULL DEFAULT '',
    UNIQUE INDEX `seq` (`seq`) USING BTREE,
    INDEX `insert_date` (`insert_date`) USING BTREE,
    INDEX `bot_id` (`bot_id`) USING BTREE,
    INDEX `request_user_plusfriend_userkey` (`request_user_plusfriend_userkey`) USING BTREE,
    INDEX `app_user_id` (`app_user_id`) USING BTREE,
    INDEX `maindb_custom_id` (`maindb_custom_id`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`kakao_skill_msg`
(
    `seq`                             INT       NOT NULL AUTO_INCREMENT,
    `insert_date`                     DATETIME      NULL DEFAULT '2021-01-01 00:00:00',
    `bot_id`                          VARCHAR(50)   NOT NULL,
    `bot_name`                        VARCHAR(100)  NULL DEFAULT '',
    `intent_id`                       VARCHAR(50)   NULL DEFAULT '',
    `intent_name`                     VARCHAR(50)   NULL DEFAULT '',
    `intent_extra_reason_code`        VARCHAR(50)   NULL DEFAULT '',
    `intent_extra_reason_message`     VARCHAR(100)  NULL DEFAULT '',
    `action_id`                       VARCHAR(50)   NULL DEFAULT '',
    `action_name`                     VARCHAR(50)   NULL DEFAULT '',
    `request_block_id`                VARCHAR(50)   NULL DEFAULT '',
    `request_block_name`              VARCHAR(50)   NULL DEFAULT '',
    `request_user_id`                 VARCHAR(100)  NULL DEFAULT '',
    `request_user_type`               VARCHAR(50)   NULL DEFAULT '',
    `request_user_isfriend`           VARCHAR(30)   NULL DEFAULT '',
    `request_user_plusfriend_userkey` VARCHAR(50)   NULL DEFAULT '',
    `request_utterance`               VARCHAR(500)  NULL DEFAULT '',
    `request_event_name`              VARCHAR(50)   NULL DEFAULT '',
    `request_event_data`              VARCHAR(500)  NULL DEFAULT '',
    `request_params_param_event_id`   VARCHAR(20)   NULL DEFAULT '',
    `request_params_surface`          VARCHAR(50)   NULL DEFAULT '',
    `request_lang`                    VARCHAR(10)   NULL DEFAULT '',
    `app_user_status`                 VARCHAR(50)   NULL DEFAULT '',
    `app_user_id`                     VARCHAR(100)  NULL DEFAULT '',
    `response_type`                   VARCHAR(30)   NULL DEFAULT '',
    `response_data`                   VARCHAR(1000) NULL DEFAULT '',
    UNIQUE INDEX `seq` (`seq`) USING BTREE,
    INDEX `insert_date` (`insert_date`) USING BTREE,
    INDEX `bot_id` (`bot_id`) USING BTREE,
    INDEX `request_user_plusfriend_userkey` (`request_user_plusfriend_userkey`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`transcribe_learn`
(
    `seq`            INT      NOT NULL AUTO_INCREMENT COMMENT '고유키',
    `company_id`     VARCHAR(30)  NULL     DEFAULT '' COMMENT '고객사 아이디',
    `groupName`      VARCHAR(100) NOT NULL DEFAULT '' COMMENT '학습그룹명',
    `learnGroupCode` VARCHAR(200) NULL     DEFAULT '' COMMENT '학습그룹코드모음',
    `learnStatus`    VARCHAR(10)  NOT NULL DEFAULT 'N' COMMENT '학습요청상태',
    `learnFileName`  VARCHAR(200) NULL     DEFAULT '' COMMENT '학습모델파일',
    PRIMARY KEY (`seq`) USING BTREE,
    INDEX `company_id` (`company_id`) USING BTREE
) COMMENT ='EICN 학습그룹' AUTO_INCREMENT = 23
;

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`maindb_custom_info`
(
    `MAINDB_SYS_CUSTOM_ID`        VARCHAR(100)  NOT NULL DEFAULT '',
    `MAINDB_SYS_UPLOAD_DATE`      DATETIME      NULL     DEFAULT '2010-01-01 00:00:00',
    `MAINDB_SYS_UPDATE_DATE`      DATETIME      NULL     DEFAULT '2010-01-01 00:00:00',
    `MAINDB_SYS_GROUP_ID`         INT       NOT NULL DEFAULT '0',
    `MAINDB_SYS_GROUP_TYPE`       INT       NOT NULL DEFAULT '0',
    `MAINDB_SYS_RESULT_TYPE`      INT       NOT NULL DEFAULT '0',
    `MAINDB_SYS_DAMDANG_ID`       VARCHAR(20)   NOT NULL DEFAULT '',
    `MAINDB_SYS_LAST_RESULT_ID`   INT       NULL     DEFAULT '0',
    `MAINDB_SYS_LAST_RESULT_DATE` DATETIME      NULL     DEFAULT '2010-01-01 00:00:00',
    `MAINDB_SYS_COMPANY_ID`       VARCHAR(50)   NOT NULL DEFAULT '',
    `MAINDB_DATE_1`               DATE          NULL     DEFAULT '2010-01-01',
    `MAINDB_DATE_2`               DATE          NULL     DEFAULT '2010-01-01',
    `MAINDB_DATE_3`               DATE          NULL     DEFAULT '2010-01-01',
    `MAINDB_DAY_1`                DATE          NULL     DEFAULT '2010-01-01',
    `MAINDB_DAY_2`                DATE          NULL     DEFAULT '2010-01-01',
    `MAINDB_DAY_3`                DATE          NULL     DEFAULT '2010-01-01',
    `MAINDB_DATETIME_1`           DATETIME      NULL     DEFAULT '2010-01-01 00:00:00',
    `MAINDB_DATETIME_2`           DATETIME      NULL     DEFAULT '2010-01-01 00:00:00',
    `MAINDB_DATETIME_3`           DATETIME      NULL     DEFAULT '2010-01-01 00:00:00',
    `MAINDB_INT_1`                INT       NULL     DEFAULT '0',
    `MAINDB_INT_2`                INT       NULL     DEFAULT '0',
    `MAINDB_INT_3`                INT       NULL     DEFAULT '0',
    `MAINDB_INT_4`                INT       NULL     DEFAULT '0',
    `MAINDB_INT_5`                INT       NULL     DEFAULT '0',
    `MAINDB_STRING_1`             VARCHAR(1000) NULL     DEFAULT '',
    `MAINDB_STRING_2`             VARCHAR(1000) NULL     DEFAULT '',
    `MAINDB_STRING_3`             VARCHAR(1000) NULL     DEFAULT '',
    `MAINDB_STRING_4`             VARCHAR(1000) NULL     DEFAULT '',
    `MAINDB_STRING_5`             VARCHAR(1000) NULL     DEFAULT '',
    `MAINDB_STRING_6`             VARCHAR(1000) NULL     DEFAULT '',
    `MAINDB_STRING_7`             VARCHAR(1000) NULL     DEFAULT '',
    `MAINDB_STRING_8`             VARCHAR(1000) NULL     DEFAULT '',
    `MAINDB_STRING_9`             VARCHAR(1000) NULL     DEFAULT '',
    `MAINDB_STRING_10`            VARCHAR(500)  NULL     DEFAULT '',
    `MAINDB_STRING_11`            VARCHAR(500)  NULL     DEFAULT '',
    `MAINDB_STRING_12`            VARCHAR(500)  NULL     DEFAULT '',
    `MAINDB_STRING_13`            VARCHAR(500)  NULL     DEFAULT '',
    `MAINDB_STRING_14`            VARCHAR(500)  NULL     DEFAULT '',
    `MAINDB_STRING_15`            VARCHAR(500)  NULL     DEFAULT '',
    `MAINDB_STRING_16`            VARCHAR(500)  NULL     DEFAULT '',
    `MAINDB_STRING_17`            VARCHAR(500)  NULL     DEFAULT '',
    `MAINDB_STRING_18`            VARCHAR(500)  NULL     DEFAULT '',
    `MAINDB_STRING_19`            VARCHAR(500)  NULL     DEFAULT '',
    `MAINDB_STRING_20`            VARCHAR(500)  NULL     DEFAULT '',
    `MAINDB_CODE_1`               VARCHAR(50)   NULL     DEFAULT '',
    `MAINDB_CODE_2`               VARCHAR(50)   NULL     DEFAULT '',
    `MAINDB_CODE_3`               VARCHAR(50)   NULL     DEFAULT '',
    `MAINDB_CODE_4`               VARCHAR(50)   NULL     DEFAULT '',
    `MAINDB_CODE_5`               VARCHAR(50)   NULL     DEFAULT '',
    `MAINDB_CODE_6`               VARCHAR(50)   NULL     DEFAULT '',
    `MAINDB_CODE_7`               VARCHAR(50)   NULL     DEFAULT '',
    `MAINDB_CODE_8`               VARCHAR(50)   NULL     DEFAULT '',
    `MAINDB_CODE_9`               VARCHAR(50)   NULL     DEFAULT '',
    `MAINDB_CODE_10`              VARCHAR(50)   NULL     DEFAULT '',
    `MAINDB_MULTICODE_1`          VARCHAR(100)  NULL     DEFAULT '',
    `MAINDB_MULTICODE_2`          VARCHAR(100)  NULL     DEFAULT '',
    `MAINDB_MULTICODE_3`          VARCHAR(100)  NULL     DEFAULT '',
    `MAINDB_IMG_1`                VARCHAR(100)  NULL     DEFAULT '',
    `MAINDB_IMG_2`                VARCHAR(100)  NULL     DEFAULT '',
    `MAINDB_IMG_3`                VARCHAR(100)  NULL     DEFAULT '',
    `MAINDB_CONCODE_1`            VARCHAR(100)  NULL     DEFAULT '',
    `MAINDB_CONCODE_2`            VARCHAR(100)  NULL     DEFAULT '',
    `MAINDB_CONCODE_3`            VARCHAR(100)  NULL     DEFAULT '',
    `MAINDB_CSCODE_1`             VARCHAR(100)  NULL     DEFAULT '',
    `MAINDB_CSCODE_2`             VARCHAR(100)  NULL     DEFAULT '',
    `MAINDB_CSCODE_3`             VARCHAR(100)  NULL     DEFAULT '',
    PRIMARY KEY (`MAINDB_SYS_CUSTOM_ID`) USING BTREE,
    INDEX `MAINDB_SYS_GROUP_TYPE` (`MAINDB_SYS_GROUP_TYPE`) USING BTREE,
    INDEX `MAINDB_SYS_GROUP_ID` (`MAINDB_SYS_GROUP_ID`) USING BTREE,
    INDEX `MAINDB_SYS_DAMDANG_ID` (`MAINDB_SYS_DAMDANG_ID`) USING BTREE,
    INDEX `MAINDB_SYS_UPLOAD_DATE` (`MAINDB_SYS_UPLOAD_DATE`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`maindb_key_info`
(
    `key_value` VARCHAR(40)  NOT NULL DEFAULT '',
    `custom_id` VARCHAR(100) NOT NULL DEFAULT '',
    `group_id`  INT      NULL     DEFAULT '0',
    PRIMARY KEY (`key_value`) USING BTREE,
    INDEX `key_value` (`custom_id`) USING BTREE,
    INDEX `group_id` (`group_id`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`maindb_multichannel_info`
(
    `seq`                INT      NOT NULL AUTO_INCREMENT,
    `channel_type`       VARCHAR(20)  NULL DEFAULT '',
    `channel_data`       VARCHAR(100) NULL DEFAULT '',
    `maindb_group_id`    INT      NULL DEFAULT '0',
    `maindb_custom_id`   VARCHAR(100) NULL DEFAULT '',
    `maindb_custom_name` VARCHAR(100) NULL DEFAULT '',
    `company_id`         VARCHAR(30)  NULL DEFAULT '',
    PRIMARY KEY (`seq`) USING BTREE,
    INDEX `channel_type` (`channel_type`) USING BTREE,
    INDEX `channel_data` (`channel_data`) USING BTREE,
    INDEX `maindb_group_id` (`maindb_group_id`) USING BTREE,
    INDEX `maindb_custom_id` (`maindb_custom_id`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`member_status`
(
    `seq`         INT     NOT NULL AUTO_INCREMENT COMMENT '고유키',
    `start_date`  DATETIME    NULL DEFAULT '2009-07-01 00:00:00' COMMENT '시작일',
    `end_date`    DATETIME    NULL DEFAULT '2009-07-01 00:00:00' COMMENT '종료일',
    `phoneid`     VARCHAR(30) NULL DEFAULT '' COMMENT '전화아이디',
    `phonename`   VARCHAR(30) NULL DEFAULT '' COMMENT '전화이름',
    `status`      CHAR(5)     NULL DEFAULT '' COMMENT '상태',
    `next_status` CHAR(5)     NULL DEFAULT '' COMMENT '다음상태',
    `in_out`      CHAR(1)     NULL DEFAULT 'I' COMMENT 'status가 1일때만 의미가 있음',
    `company_id`  VARCHAR(30) NULL DEFAULT '' COMMENT '회사아이디',
    PRIMARY KEY (`seq`) USING BTREE,
    INDEX `phoneid` (`phoneid`) USING BTREE,
    INDEX `start_date` (`start_date`) USING BTREE,
    INDEX `status` (`status`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`memo`
(
    `id`         BIGINT   NOT NULL AUTO_INCREMENT COMMENT '식별자',
    `company_id` VARCHAR(30)  NOT NULL COMMENT '회사',
    `content`    TEXT         NULL     DEFAULT NULL COMMENT '메모',
    `user`       VARCHAR(100) NULL     DEFAULT NULL COMMENT '작성자',
    `created_at` TIMESTAMP    NOT NULL DEFAULT current_timestamp() COMMENT '생성시각',
    `updated_at` TIMESTAMP    NULL     DEFAULT NULL COMMENT '갱신시각',
    `deleted_at` TIMESTAMP    NULL     DEFAULT NULL COMMENT '삭제시각',
    `title`      VARCHAR(128) NOT NULL COMMENT '북마크된',
    `bookmarked` TINYINT   NOT NULL DEFAULT '0' COMMENT '북마크된',
    PRIMARY KEY (`id`) USING BTREE,
    INDEX `company_id` (`company_id`) USING BTREE,
    INDEX `user` (`user`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`memo_msg`
(
    `seq`            INT       NOT NULL AUTO_INCREMENT,
    `message_id`     VARCHAR(100)  NULL     DEFAULT '' COMMENT '메모메세지아이디',
    `send_userid`    VARCHAR(30)   NULL     DEFAULT '' COMMENT '메모발신자아이디',
    `receive_userid` VARCHAR(30)   NULL     DEFAULT '' COMMENT '메모수신자아이디',
    `insert_time`    DATETIME      NOT NULL DEFAULT '2009-07-01 00:00:00' COMMENT '메세지인서트시간',
    `send_receive`   CHAR(3)       NULL     DEFAULT 'S' COMMENT 'S-발신 R-수신',
    `read_yn`        CHAR(1)       NULL     DEFAULT 'Y' COMMENT '읽음여부',
    `content`        VARCHAR(1100) NOT NULL DEFAULT '' COMMENT '메세지',
    UNIQUE INDEX `seq` (`seq`) USING BTREE,
    INDEX `message_id` (`message_id`) USING BTREE,
    INDEX `insert_time` (`insert_time`) USING BTREE,
    INDEX `send_userid` (`send_userid`) USING BTREE,
    INDEX `receive_userid` (`receive_userid`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`message_data`
(
    `seq`              INT       NOT NULL AUTO_INCREMENT,
    `send_cli_key`     VARCHAR(50)   NULL DEFAULT '' COMMENT '메세지아이디',
    `title`            VARCHAR(50)   NULL DEFAULT '' COMMENT 'MMS타이틀',
    `status`           CHAR(1)       NULL DEFAULT '' COMMENT '상태S,R',
    `result_status`    CHAR(1)       NULL DEFAULT '' COMMENT '상태S,R',
    `confirm_status`   CHAR(1)       NULL DEFAULT '' COMMENT '상태S,R',
    `insert_time`      DATETIME      NULL DEFAULT '2009-07-01 00:00:00',
    `send_time`        DATETIME      NULL DEFAULT '2009-07-01 00:00:00',
    `result_time`      DATETIME      NULL DEFAULT '2009-07-01 00:00:00',
    `confirm_time`     DATETIME      NULL DEFAULT '2009-07-01 00:00:00',
    `service`          CHAR(10)      NULL DEFAULT '' COMMENT 'SMS,MMS,LMS,KAKAO,RCS',
    `callback`         VARCHAR(50)   NULL DEFAULT '' COMMENT '발신번호',
    `phone_number`     VARCHAR(50)   NULL DEFAULT '' COMMENT '수신번호',
    `message`          VARCHAR(2000) NULL DEFAULT NULL,
    `userid`           VARCHAR(30)   NULL DEFAULT '' COMMENT '상담사아이디',
    `project_id`       VARCHAR(50)   NULL DEFAULT '' COMMENT '메세지허브프로젝트아이디',
    `api_key`          VARCHAR(50)   NULL DEFAULT '' COMMENT '메세지허브프로젝트API키',
    `attach_file`      VARCHAR(100)  NULL DEFAULT '' COMMENT '첨부파일명',
    `company_id`       VARCHAR(50)   NULL DEFAULT '' COMMENT '회사아이디',
    `res_data_msgkey`  VARCHAR(100)  NULL DEFAULT '' COMMENT '결과메세지',
    `res_code`         VARCHAR(10)   NULL DEFAULT '' COMMENT '결과코드',
    `res_message`      VARCHAR(100)  NULL DEFAULT '' COMMENT '결과메세지',
    `res_data_code`    VARCHAR(10)   NULL DEFAULT '' COMMENT '메세지발송코드',
    `res_data_message` VARCHAR(100)  NULL DEFAULT '' COMMENT '메세지발송메세지',
    `confirm_code`     VARCHAR(10)   NULL DEFAULT '' COMMENT '메세지발송코드',
    `confirm_message`  VARCHAR(100)  NULL DEFAULT '' COMMENT '메세지발송메세지',
    `telco`            VARCHAR(20)   NULL DEFAULT '' COMMENT '통신사',
    `retry_cnt`        INT       NULL DEFAULT '0' COMMENT '재전송횟수',
    UNIQUE INDEX `seq` (`seq`) USING BTREE,
    INDEX `send_cli_key` (`send_cli_key`) USING BTREE,
    INDEX `insert_time` (`insert_time`) USING BTREE,
    INDEX `userid` (`userid`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`prohibited_keyword`
(
    `keyword`       VARCHAR(100) NOT NULL COMMENT '키워드',
    `creator`       VARCHAR(100) NULL     DEFAULT NULL COMMENT '작성자',
    `created_at`    TIMESTAMP    NOT NULL DEFAULT current_timestamp() COMMENT '생성시각',
    `prohibit_yn`   CHAR(1)      NULL     DEFAULT 'N' COMMENT '금지어여부',
    `keyword_yn`    CHAR(1)      NULL     DEFAULT 'N' COMMENT '어드민등록키워드여부',
    `kmshashtag_yn` CHAR(1)      NULL     DEFAULT 'N' COMMENT 'KMS해쉬태그여부',
    `company_id`    VARCHAR(30)  NOT NULL COMMENT '회사',
    PRIMARY KEY (`company_id`, `keyword`) USING BTREE,
    INDEX `creator` (`creator`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`prv_custom_info`
(
    `PRV_SYS_CUSTOM_ID`          VARCHAR(100)  NOT NULL DEFAULT '',
    `PRV_SYS_UPLOAD_DATE`        DATETIME      NULL     DEFAULT '2010-01-01 00:00:00',
    `PRV_SYS_UPDATE_DATE`        DATETIME      NULL     DEFAULT '2010-01-01 00:00:00',
    `PRV_SYS_GROUP_ID`           INT       NOT NULL DEFAULT '0',
    `PRV_SYS_GROUP_TYPE`         INT       NOT NULL DEFAULT '0',
    `PRV_SYS_RESULT_TYPE`        INT       NOT NULL DEFAULT '0',
    `PRV_SYS_DAMDANG_ID`         VARCHAR(20)   NOT NULL DEFAULT '',
    `PRV_SYS_RID_NUMBER`         VARCHAR(20)   NOT NULL DEFAULT '',
    `PRV_SYS_LAST_RESULT_ID`     INT       NULL     DEFAULT '0',
    `PRV_SYS_LAST_RESULT_DATE`   DATETIME      NULL     DEFAULT '2010-01-01 00:00:00',
    `PRV_SYS_LAST_CALL_DATE`     DATETIME      NULL     DEFAULT '2010-01-01 00:00:00',
    `PRV_SYS_LAST_HANGUP_CAUSE`  VARCHAR(30)   NULL     DEFAULT '',
    `PRV_SYS_LAST_CALL_UNIQUEID` VARCHAR(50)   NULL     DEFAULT '',
    `PRV_SYS_COMPANY_ID`         VARCHAR(50)   NOT NULL DEFAULT '',
    `PRV_DATE_1`                 DATE          NULL     DEFAULT '2010-01-01',
    `PRV_DATE_2`                 DATE          NULL     DEFAULT '2010-01-01',
    `PRV_DATE_3`                 DATE          NULL     DEFAULT '2010-01-01',
    `PRV_DAY_1`                  DATE          NULL     DEFAULT '2010-01-01',
    `PRV_DAY_2`                  DATE          NULL     DEFAULT '2010-01-01',
    `PRV_DAY_3`                  DATE          NULL     DEFAULT '2010-01-01',
    `PRV_DATETIME_1`             DATETIME      NULL     DEFAULT '2010-01-01 00:00:00',
    `PRV_DATETIME_2`             DATETIME      NULL     DEFAULT '2010-01-01 00:00:00',
    `PRV_DATETIME_3`             DATETIME      NULL     DEFAULT '2010-01-01 00:00:00',
    `PRV_INT_1`                  INT       NULL     DEFAULT '0',
    `PRV_INT_2`                  INT       NULL     DEFAULT '0',
    `PRV_INT_3`                  INT       NULL     DEFAULT '0',
    `PRV_INT_4`                  INT       NULL     DEFAULT '0',
    `PRV_INT_5`                  INT       NULL     DEFAULT '0',
    `PRV_NUMBER_1`               VARCHAR(15)   NULL     DEFAULT '',
    `PRV_NUMBER_2`               VARCHAR(15)   NULL     DEFAULT '',
    `PRV_NUMBER_3`               VARCHAR(15)   NULL     DEFAULT '',
    `PRV_NUMBER_4`               VARCHAR(15)   NULL     DEFAULT '',
    `PRV_NUMBER_5`               VARCHAR(15)   NULL     DEFAULT '',
    `PRV_STRING_1`               VARCHAR(1000) NULL     DEFAULT '',
    `PRV_STRING_2`               VARCHAR(1000) NULL     DEFAULT '',
    `PRV_STRING_3`               VARCHAR(1000) NULL     DEFAULT '',
    `PRV_STRING_4`               VARCHAR(1000) NULL     DEFAULT '',
    `PRV_STRING_5`               VARCHAR(1000) NULL     DEFAULT '',
    `PRV_STRING_6`               VARCHAR(1000) NULL     DEFAULT '',
    `PRV_STRING_7`               VARCHAR(1000) NULL     DEFAULT '',
    `PRV_STRING_8`               VARCHAR(1000) NULL     DEFAULT '',
    `PRV_STRING_9`               VARCHAR(1000) NULL     DEFAULT '',
    `PRV_STRING_10`              VARCHAR(500)  NULL     DEFAULT '',
    `PRV_STRING_11`              VARCHAR(500)  NULL     DEFAULT '',
    `PRV_STRING_12`              VARCHAR(500)  NULL     DEFAULT '',
    `PRV_STRING_13`              VARCHAR(500)  NULL     DEFAULT '',
    `PRV_STRING_14`              VARCHAR(500)  NULL     DEFAULT '',
    `PRV_STRING_15`              VARCHAR(500)  NULL     DEFAULT '',
    `PRV_STRING_16`              VARCHAR(500)  NULL     DEFAULT '',
    `PRV_STRING_17`              VARCHAR(500)  NULL     DEFAULT '',
    `PRV_STRING_18`              VARCHAR(500)  NULL     DEFAULT '',
    `PRV_STRING_19`              VARCHAR(500)  NULL     DEFAULT '',
    `PRV_STRING_20`              VARCHAR(500)  NULL     DEFAULT '',
    `PRV_CODE_1`                 VARCHAR(50)   NULL     DEFAULT '',
    `PRV_CODE_2`                 VARCHAR(50)   NULL     DEFAULT '',
    `PRV_CODE_3`                 VARCHAR(50)   NULL     DEFAULT '',
    `PRV_CODE_4`                 VARCHAR(50)   NULL     DEFAULT '',
    `PRV_CODE_5`                 VARCHAR(50)   NULL     DEFAULT '',
    `PRV_CODE_6`                 VARCHAR(50)   NULL     DEFAULT '',
    `PRV_CODE_7`                 VARCHAR(50)   NULL     DEFAULT '',
    `PRV_CODE_8`                 VARCHAR(50)   NULL     DEFAULT '',
    `PRV_CODE_9`                 VARCHAR(50)   NULL     DEFAULT '',
    `PRV_CODE_10`                VARCHAR(50)   NULL     DEFAULT '',
    `PRV_MULTICODE_1`            VARCHAR(100)  NULL     DEFAULT '',
    `PRV_MULTICODE_2`            VARCHAR(100)  NULL     DEFAULT '',
    `PRV_MULTICODE_3`            VARCHAR(100)  NULL     DEFAULT '',
    `PRV_CONCODE_1`              VARCHAR(50)   NULL     DEFAULT '',
    `PRV_CONCODE_2`              VARCHAR(50)   NULL     DEFAULT '',
    `PRV_CONCODE_3`              VARCHAR(50)   NULL     DEFAULT '',
    `PRV_CSCODE_1`               VARCHAR(50)   NULL     DEFAULT '',
    `PRV_CSCODE_2`               VARCHAR(50)   NULL     DEFAULT '',
    `PRV_CSCODE_3`               VARCHAR(50)   NULL     DEFAULT '',
    PRIMARY KEY (`PRV_SYS_CUSTOM_ID`) USING BTREE,
    INDEX `PRV_SYS_GROUP_ID` (`PRV_SYS_GROUP_ID`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`result_custom_info`
(
    `seq`            INT          NOT NULL AUTO_INCREMENT,
    `company_id`     VARCHAR(30)      NOT NULL DEFAULT '',
    `result_date`    DATETIME         NOT NULL DEFAULT '2010-01-01 00:00:00',
    `update_date`    DATETIME         NOT NULL DEFAULT '2010-01-01 00:00:00',
    `uniqueid`       VARCHAR(50)      NULL     DEFAULT '',
    `hangup_cause`   VARCHAR(50)      NULL     DEFAULT '',
    `hangup_msg`     VARCHAR(100)     NULL     DEFAULT '',
    `billsec`        INT          NULL     DEFAULT '0',
    `custom_id`      VARCHAR(50)      NULL     DEFAULT '',
    `click_key`      VARCHAR(50)      NULL     DEFAULT '',
    `custom_number`  VARCHAR(50)      NOT NULL DEFAULT '',
    `execute_id`     VARCHAR(50)      NULL     DEFAULT '',
    `group_id`       INT UNSIGNED NULL     DEFAULT '0',
    `userid`         VARCHAR(30)      NULL     DEFAULT '',
    `userid_org`     VARCHAR(30)      NULL     DEFAULT '',
    `userid_tr`      VARCHAR(30)      NULL     DEFAULT '',
    `result_type`    INT          NULL     DEFAULT '0',
    `call_type`      VARCHAR(5)       NULL     DEFAULT '',
    `from_org`       VARCHAR(20)      NULL     DEFAULT '',
    `group_kind`     VARCHAR(10)      NULL     DEFAULT '',
    `group_type`     INT          NULL     DEFAULT '0',
    `RS_DATE_1`      DATE             NULL     DEFAULT '2010-01-01',
    `RS_DATE_2`      DATE             NULL     DEFAULT '2010-01-01',
    `RS_DATE_3`      DATE             NULL     DEFAULT '2010-01-01',
    `RS_DAY_1`       DATE             NULL     DEFAULT '2010-01-01',
    `RS_DAY_2`       DATE             NULL     DEFAULT '2010-01-01',
    `RS_DAY_3`       DATE             NULL     DEFAULT '2010-01-01',
    `RS_DATETIME_1`  DATETIME         NULL     DEFAULT '2010-01-01 00:00:00',
    `RS_DATETIME_2`  DATETIME         NULL     DEFAULT '2010-01-01 00:00:00',
    `RS_DATETIME_3`  DATETIME         NULL     DEFAULT '2010-01-01 00:00:00',
    `RS_INT_1`       INT          NULL     DEFAULT '0',
    `RS_INT_2`       INT          NULL     DEFAULT '0',
    `RS_INT_3`       INT          NULL     DEFAULT '0',
    `RS_INT_4`       INT          NULL     DEFAULT '0',
    `RS_INT_5`       INT          NULL     DEFAULT '0',
    `RS_NUMBER_1`    VARCHAR(15)      NULL     DEFAULT '',
    `RS_NUMBER_2`    VARCHAR(15)      NULL     DEFAULT '',
    `RS_NUMBER_3`    VARCHAR(15)      NULL     DEFAULT '',
    `RS_NUMBER_4`    VARCHAR(15)      NULL     DEFAULT '',
    `RS_NUMBER_5`    VARCHAR(15)      NULL     DEFAULT '',
    `RS_STRING_1`    VARCHAR(1000)    NULL     DEFAULT '',
    `RS_STRING_2`    VARCHAR(1000)    NULL     DEFAULT '',
    `RS_STRING_3`    VARCHAR(1000)    NULL     DEFAULT '',
    `RS_STRING_4`    VARCHAR(1000)    NULL     DEFAULT '',
    `RS_STRING_5`    VARCHAR(1000)    NULL     DEFAULT '',
    `RS_STRING_6`    VARCHAR(1000)    NULL     DEFAULT '',
    `RS_STRING_7`    VARCHAR(1000)    NULL     DEFAULT '',
    `RS_STRING_8`    VARCHAR(1000)    NULL     DEFAULT '',
    `RS_STRING_9`    VARCHAR(1000)    NULL     DEFAULT '',
    `RS_STRING_10`   VARCHAR(500)     NULL     DEFAULT '',
    `RS_STRING_11`   VARCHAR(500)     NULL     DEFAULT '',
    `RS_STRING_12`   VARCHAR(500)     NULL     DEFAULT '',
    `RS_STRING_13`   VARCHAR(500)     NULL     DEFAULT '',
    `RS_STRING_14`   VARCHAR(500)     NULL     DEFAULT '',
    `RS_STRING_15`   VARCHAR(500)     NULL     DEFAULT '',
    `RS_STRING_16`   VARCHAR(500)     NULL     DEFAULT '',
    `RS_STRING_17`   VARCHAR(500)     NULL     DEFAULT '',
    `RS_STRING_18`   VARCHAR(500)     NULL     DEFAULT '',
    `RS_STRING_19`   VARCHAR(500)     NULL     DEFAULT '',
    `RS_STRING_20`   VARCHAR(500)     NULL     DEFAULT '',
    `RS_CODE_1`      VARCHAR(50)      NULL     DEFAULT '',
    `RS_CODE_2`      VARCHAR(50)      NULL     DEFAULT '',
    `RS_CODE_3`      VARCHAR(50)      NULL     DEFAULT '',
    `RS_CODE_4`      VARCHAR(50)      NULL     DEFAULT '',
    `RS_CODE_5`      VARCHAR(50)      NULL     DEFAULT '',
    `RS_CODE_6`      VARCHAR(50)      NULL     DEFAULT '',
    `RS_CODE_7`      VARCHAR(50)      NULL     DEFAULT '',
    `RS_CODE_8`      VARCHAR(50)      NULL     DEFAULT '',
    `RS_CODE_9`      VARCHAR(50)      NULL     DEFAULT '',
    `RS_CODE_10`     VARCHAR(50)      NULL     DEFAULT '',
    `RS_MULTICODE_1` VARCHAR(100)     NULL     DEFAULT '',
    `RS_MULTICODE_2` VARCHAR(100)     NULL     DEFAULT '',
    `RS_MULTICODE_3` VARCHAR(100)     NULL     DEFAULT '',
    `RS_IMG_1`       VARCHAR(100)     NULL     DEFAULT '',
    `RS_IMG_2`       VARCHAR(100)     NULL     DEFAULT '',
    `RS_IMG_3`       VARCHAR(100)     NULL     DEFAULT '',
    `RS_CONCODE_1`   VARCHAR(50)      NULL     DEFAULT '',
    `RS_CONCODE_2`   VARCHAR(50)      NULL     DEFAULT '',
    `RS_CONCODE_3`   VARCHAR(50)      NULL     DEFAULT '',
    `RS_CSCODE_1`    VARCHAR(50)      NULL     DEFAULT '',
    `RS_CSCODE_2`    VARCHAR(50)      NULL     DEFAULT '',
    `RS_CSCODE_3`    VARCHAR(50)      NULL     DEFAULT '',
    PRIMARY KEY (`seq`) USING BTREE,
    INDEX `result_date` (`result_date`) USING BTREE,
    INDEX `uniqueid` (`uniqueid`) USING BTREE,
    INDEX `custom_id` (`custom_id`) USING BTREE,
    INDEX `custom_number` (`custom_number`) USING BTREE,
    INDEX `group_id` (`group_id`) USING BTREE,
    INDEX `userid` (`userid`) USING BTREE,
    INDEX `group_kind` (`group_kind`) USING BTREE,
    INDEX `click_key` (`click_key`) USING BTREE,
    INDEX `userid_tr` (`userid_tr`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`stt_cdr`
(
    `start_time`     DATETIME     NULL     DEFAULT '2010-01-01 01:00:00' COMMENT '통화시작',
    `end_time`       DATETIME     NULL     DEFAULT '2010-01-01 01:00:00' COMMENT '통화종료',
    `call_status`    CHAR(1)      NULL     DEFAULT 'D',
    `call_uniqueid`  VARCHAR(50)  NOT NULL DEFAULT '',
    `in_out`         VARCHAR(5)   NULL     DEFAULT 'I',
    `ipcc_userid`    VARCHAR(50)  NOT NULL DEFAULT '',
    `ipcc_username`  VARCHAR(50)  NULL     DEFAULT '',
    `custom_number`  VARCHAR(20)  NULL     DEFAULT '',
    `extension`      VARCHAR(20)  NULL     DEFAULT '',
    `service_number` VARCHAR(20)  NULL     DEFAULT '',
    `message_yn`     CHAR(1)      NULL     DEFAULT '',
    `company_id`     VARCHAR(30)  NOT NULL DEFAULT '' COMMENT '컴퍼니아이디',
    `etc1`           VARCHAR(100) NULL     DEFAULT '',
    `etc2`           VARCHAR(100) NULL     DEFAULT '',
    `etc3`           VARCHAR(100) NULL     DEFAULT '',
    PRIMARY KEY (`company_id`, `ipcc_userid`, `call_uniqueid`) USING BTREE,
    INDEX `start_time` (`start_time`) USING BTREE,
    INDEX `end_time` (`end_time`) USING BTREE,
    INDEX `call_uniqueid` (`call_uniqueid`) USING BTREE,
    INDEX `ipcc_userid` (`ipcc_userid`) USING BTREE,
    INDEX `custom_number` (`custom_number`) USING BTREE,
    INDEX `extension` (`extension`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`stt_message`
(
    `seq`           INT      NOT NULL AUTO_INCREMENT,
    `message_id`    VARCHAR(50)  NULL     DEFAULT '',
    `insert_time`   DATETIME     NOT NULL DEFAULT '2009-07-01 00:00:00',
    `call_uniqueid` VARCHAR(50)  NULL     DEFAULT '',
    `userid`        VARCHAR(50)  NULL     DEFAULT '',
    `target_userid` VARCHAR(50)  NULL     DEFAULT '',
    `message`       VARCHAR(500) NULL     DEFAULT '',
    UNIQUE INDEX `seq` (`seq`) USING BTREE,
    INDEX `insert_time` (`insert_time`) USING BTREE,
    INDEX `userid` (`userid`) USING BTREE,
    INDEX `target_userid` (`target_userid`) USING BTREE,
    INDEX `call_uniqueid` (`call_uniqueid`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`stt_text`
(
    `seq`           INT      NOT NULL AUTO_INCREMENT,
    `message_id`    VARCHAR(50)  NULL     DEFAULT '',
    `insert_time`   DATETIME     NOT NULL DEFAULT '2009-07-01 00:00:00',
    `call_uniqueid` VARCHAR(50)  NULL     DEFAULT '',
    `ipcc_userid`   VARCHAR(50)  NULL     DEFAULT '',
    `my_extension`  VARCHAR(20)  NULL     DEFAULT '',
    `kind`          VARCHAR(20)  NULL     DEFAULT '',
    `text`          VARCHAR(500) NULL     DEFAULT '',
    `start_ms`      INT      NULL     DEFAULT '0',
    `stop_ms`       INT      NULL     DEFAULT '0',
    `kms_keyword`   VARCHAR(500) NOT NULL DEFAULT '',
    `remind_yn`     CHAR(1)      NULL     DEFAULT 'N',
    UNIQUE INDEX `seq` (`seq`) USING BTREE,
    INDEX `insert_time` (`insert_time`) USING BTREE,
    INDEX `ipcc_userid` (`ipcc_userid`) USING BTREE,
    INDEX `call_uniqueid` (`call_uniqueid`) USING BTREE,
    INDEX `message_id` (`message_id`) USING BTREE,
    INDEX `remind_yn` (`remind_yn`) USING BTREE,
    INDEX `my_extension` (`my_extension`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`transcribe_data`
(
    `seq`        INT      NOT NULL AUTO_INCREMENT COMMENT '고유키',
    `company_id` VARCHAR(30)  NULL     DEFAULT '' COMMENT '고객사 아이디',
    `groupCode`  INT      NOT NULL COMMENT '전사그룹코드',
    `filePath`   VARCHAR(200) NOT NULL DEFAULT '' COMMENT '전사파일경로',
    `fileName`   VARCHAR(200) NULL     DEFAULT '' COMMENT '전사파일명',
    `userId`     VARCHAR(30)  NULL     DEFAULT '' COMMENT '전사상담원ID',
    `hypInfo`    LONGTEXT     NULL     DEFAULT '' COMMENT 'STT정보' COLLATE 'utf8mb4_bin',
    `refInfo`    LONGTEXT     NULL     DEFAULT '' COMMENT '전사처리정보' COLLATE 'utf8mb4_bin',
    `status`     VARCHAR(10)  NULL     DEFAULT '' COMMENT '처리상태',
    `sttStatus`  VARCHAR(10)  NULL     DEFAULT 'N' COMMENT 'STT 요청상태',
    `recStatus`  VARCHAR(10)  NULL     DEFAULT 'N' COMMENT '인식률측정 요청상태',
    `learn`      VARCHAR(10)  NULL     DEFAULT '',
    `nRate`      DOUBLE       NULL     DEFAULT '0' COMMENT 'N인식률',
    `dRate`      DOUBLE       NULL     DEFAULT '0' COMMENT 'D인식률',
    `sRate`      DOUBLE       NULL     DEFAULT '0' COMMENT 'S인식률',
    `iRate`      DOUBLE       NULL     DEFAULT '0' COMMENT 'I인식률',
    `aRate`      DOUBLE       NULL     DEFAULT '0' COMMENT 'A인식률',
    PRIMARY KEY (`seq`) USING BTREE,
    INDEX `groupCode` (`groupCode`) USING BTREE,
    INDEX `fileName` (`fileName`) USING BTREE,
    INDEX `userId` (`userId`) USING BTREE
) COMMENT ='EICN 전사그룹별 파일관리';

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`transcribe_group`
(
    `seq`        INT      NOT NULL AUTO_INCREMENT,
    `company_id` VARCHAR(30)  NULL DEFAULT '' COMMENT '컴퍼니아이디',
    `groupName`  VARCHAR(100) NULL DEFAULT '' COMMENT '전사그룹명',
    `userId`     VARCHAR(30)  NULL DEFAULT '' COMMENT '그룹담당자ID',
    `status`     VARCHAR(10)  NULL DEFAULT 'A' COMMENT '그룹진행상태',
    `fileCnt`    INT      NULL DEFAULT '0' COMMENT '녹취파일갯수',
    `recRate`    DOUBLE       NULL DEFAULT '0' COMMENT '인식률',
    PRIMARY KEY (`seq`) USING BTREE,
    INDEX `status` (`status`) USING BTREE,
    INDEX `userId` (`userId`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`voc_custom_list`
(
    `seq`           INT     NOT NULL AUTO_INCREMENT COMMENT 'SEQUENCE KEY',
    `insert_date`   DATETIME    NULL     DEFAULT '2020-01-01 00:00:00',
    `voc_group_id`  INT     NULL     DEFAULT '0' COMMENT 'VOC_HAPPYCALL그룹 아이디',
    `sender`        VARCHAR(10) NULL     DEFAULT 'MEMBER' COMMENT '진행을 결정하는 주체 MEMBER-상담사가 화면에서인서트함 AUTO-자동으로 조건이 맞아서 시스템에서 인서트',
    `custom_number` VARCHAR(30) NOT NULL DEFAULT '' COMMENT 'HAPPYCALL대상고객전화번호',
    `company_id`    VARCHAR(30) NULL     DEFAULT '',
    UNIQUE INDEX `seq` (`seq`) USING BTREE,
    INDEX `insert_date` (`insert_date`) USING BTREE,
    INDEX `company_id` (`company_id`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`voc_research_result`
(
    `seq`           INT      NOT NULL AUTO_INCREMENT,
    `company_id`    VARCHAR(30)  NOT NULL DEFAULT '',
    `result_date`   TIMESTAMP    NOT NULL DEFAULT '2009-12-31 15:00:00',
    `uniqueid`      VARCHAR(50)  NOT NULL DEFAULT '',
    `hangup_cause`  VARCHAR(50)  NULL     DEFAULT '',
    `hangup_msg`    VARCHAR(100) NULL     DEFAULT '',
    `billsec`       INT      NULL     DEFAULT '0',
    `click_key`     VARCHAR(100) NULL     DEFAULT '',
    `custom_number` VARCHAR(50)  NOT NULL DEFAULT '',
    `voc_group_id`  INT      NULL     DEFAULT '0',
    `userid`        VARCHAR(30)  NULL     DEFAULT '',
    `extension`     VARCHAR(30)  NULL     DEFAULT '',
    `research_id`   INT      NULL     DEFAULT '0',
    `tree_path`     VARCHAR(800) NULL     DEFAULT '',
    `my_path_1`     VARCHAR(20)  NULL     DEFAULT '',
    `my_path_2`     VARCHAR(20)  NULL     DEFAULT '',
    `my_path_3`     VARCHAR(20)  NULL     DEFAULT '',
    `my_path_4`     VARCHAR(20)  NULL     DEFAULT '',
    `my_path_5`     VARCHAR(20)  NULL     DEFAULT '',
    `my_path_6`     VARCHAR(20)  NULL     DEFAULT '',
    `my_path_7`     VARCHAR(20)  NULL     DEFAULT '',
    `my_path_8`     VARCHAR(20)  NULL     DEFAULT '',
    `my_path_9`     VARCHAR(20)  NULL     DEFAULT '',
    `my_path_10`    VARCHAR(20)  NULL     DEFAULT '',
    `my_path_11`    VARCHAR(20)  NULL     DEFAULT '',
    `my_path_12`    VARCHAR(20)  NULL     DEFAULT '',
    `my_path_13`    VARCHAR(20)  NULL     DEFAULT '',
    `my_path_14`    VARCHAR(20)  NULL     DEFAULT '',
    `my_path_15`    VARCHAR(20)  NULL     DEFAULT '',
    `my_path_16`    VARCHAR(20)  NULL     DEFAULT '',
    `my_path_17`    VARCHAR(20)  NULL     DEFAULT '',
    `my_path_18`    VARCHAR(20)  NULL     DEFAULT '',
    `my_path_19`    VARCHAR(20)  NULL     DEFAULT '',
    `my_path_20`    VARCHAR(20)  NULL     DEFAULT '',
    PRIMARY KEY (`seq`) USING BTREE,
    INDEX `my_path_1` (`my_path_1`) USING BTREE,
    INDEX `my_path_10` (`my_path_10`) USING BTREE,
    INDEX `my_path_11` (`my_path_11`) USING BTREE,
    INDEX `my_path_12` (`my_path_12`) USING BTREE,
    INDEX `my_path_13` (`my_path_13`) USING BTREE,
    INDEX `my_path_14` (`my_path_14`) USING BTREE,
    INDEX `my_path_15` (`my_path_15`) USING BTREE,
    INDEX `my_path_16` (`my_path_16`) USING BTREE,
    INDEX `my_path_17` (`my_path_17`) USING BTREE,
    INDEX `my_path_18` (`my_path_18`) USING BTREE,
    INDEX `my_path_19` (`my_path_19`) USING BTREE,
    INDEX `my_path_2` (`my_path_2`) USING BTREE,
    INDEX `my_path_20` (`my_path_20`) USING BTREE,
    INDEX `my_path_3` (`my_path_3`) USING BTREE,
    INDEX `my_path_4` (`my_path_4`) USING BTREE,
    INDEX `my_path_5` (`my_path_5`) USING BTREE,
    INDEX `my_path_6` (`my_path_6`) USING BTREE,
    INDEX `my_path_7` (`my_path_7`) USING BTREE,
    INDEX `my_path_8` (`my_path_8`) USING BTREE,
    INDEX `my_path_9` (`my_path_9`) USING BTREE,
    INDEX `research_id` (`research_id`) USING BTREE,
    INDEX `company_id` (`company_id`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`voc_result`
(
    `seq`           INT      NOT NULL AUTO_INCREMENT COMMENT 'SEQUENCE KEY',
    `result_date`   DATETIME     NOT NULL DEFAULT '2010-01-01 00:00:00' COMMENT '설문일시',
    `uniqueid`      VARCHAR(50)  NOT NULL DEFAULT '' COMMENT '유니크 아이디',
    `hangup_cause`  VARCHAR(50)  NULL     DEFAULT '' COMMENT '전화행업코드',
    `hangup_msg`    VARCHAR(100) NULL     DEFAULT '' COMMENT '전화행업메시지',
    `billsec`       INT      NULL     DEFAULT '0' COMMENT '통화시간',
    `custom_number` VARCHAR(50)  NOT NULL DEFAULT '' COMMENT '고객 전화번호',
    `userid`        VARCHAR(30)  NULL     DEFAULT '' COMMENT '상담자',
    `voc_group_id`  INT      NULL     DEFAULT '0' COMMENT 'VOC그룹 아이디',
    `research_id`   INT      NULL     DEFAULT '0' COMMENT '설문 아이디',
    `tree_path`     VARCHAR(800) NULL     DEFAULT '' COMMENT '설문단계',
    `company_id`    VARCHAR(30)  NOT NULL DEFAULT '' COMMENT '고객사 아이디',
    PRIMARY KEY (`seq`) USING BTREE,
    INDEX `voc_group_id` (`voc_group_id`) USING BTREE,
    INDEX `research_id` (`research_id`) USING BTREE,
    INDEX `tree_path` (`tree_path`(333)) USING BTREE,
    INDEX `company_id` (`company_id`) USING BTREE
) COMMENT ='VOC 결과이력 테이블';

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`wtalk_msg`
(
    `seq`            INT       NOT NULL AUTO_INCREMENT,
    `room_id`        VARCHAR(150)  NULL     DEFAULT '',
    `channel_type`   VARCHAR(20)   NULL     DEFAULT 'eicn',
    `insert_time`    DATETIME      NOT NULL DEFAULT '2009-07-01 00:00:00',
    `send_receive`   VARCHAR(10)   NULL     DEFAULT '',
    `company_id`     VARCHAR(30)   NULL     DEFAULT '',
    `userid`         VARCHAR(30)   NULL     DEFAULT '',
    `user_key`       VARCHAR(100)  NOT NULL DEFAULT '',
    `sender_key`     VARCHAR(100)  NOT NULL DEFAULT '',
    `message_id`     VARCHAR(100)  NULL     DEFAULT '',
    `time`           VARCHAR(30)   NOT NULL DEFAULT '',
    `type`           VARCHAR(10)   NOT NULL DEFAULT '',
    `content`        VARCHAR(5000) NULL     DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    `attachment`     VARCHAR(300)  NOT NULL DEFAULT '',
    `extra`          VARCHAR(500)  NOT NULL DEFAULT '',
    `delete_request` CHAR(1)       NULL     DEFAULT '',
    UNIQUE INDEX `seq` (`seq`) USING BTREE,
    INDEX `insert_time` (`insert_time`) USING BTREE,
    INDEX `user_key` (`user_key`) USING BTREE,
    INDEX `userid` (`userid`) USING BTREE,
    INDEX `room_id` (`room_id`) USING BTREE
) AUTO_INCREMENT = 157
;

CREATE TABLE IF NOT EXISTS `CUSTOMDB`.`wtalk_room`
(
    `seq`                     INT       NOT NULL AUTO_INCREMENT,
    `room_id`                 VARCHAR(150)  NULL     DEFAULT '',
    `room_start_time`         DATETIME      NULL     DEFAULT '2009-07-01 00:00:00',
    `room_last_time`          DATETIME      NULL     DEFAULT '2009-07-01 00:00:00',
    `room_status`             CHAR(1)       NULL     DEFAULT 'S',
    `room_mode`               VARCHAR(10)   NULL     DEFAULT 'service',
    `maindb_group_id`         INT       NULL     DEFAULT '0',
    `maindb_custom_id`        VARCHAR(100)  NULL     DEFAULT '',
    `maindb_custom_name`      VARCHAR(100)  NULL     DEFAULT '',
    `auth_phone_number`       VARCHAR(50)   NULL     DEFAULT '',
    `userid`                  VARCHAR(30)   NULL     DEFAULT '',
    `user_key`                VARCHAR(100)  NOT NULL DEFAULT '',
    `channel_type`            VARCHAR(20)   NOT NULL DEFAULT 'eicn',
    `sender_key`              VARCHAR(100)  NOT NULL DEFAULT '',
    `company_id`              VARCHAR(30)   NULL     DEFAULT '',
    `room_name`               VARCHAR(100)  NULL     DEFAULT '',
    `schedule_kind`           CHAR(1)       NOT NULL DEFAULT 'D',
    `schedule_data`           VARCHAR(50)   NULL     DEFAULT '',
    `schedule_stat_yn`        CHAR(1)       NULL     DEFAULT 'Y',
    `schedule_worktime_yn`    CHAR(1)       NULL     DEFAULT 'Y',
    `is_auto_enable`          CHAR(1)       NULL     DEFAULT 'Y',
    `is_custom_upload_enable` CHAR(1)       NULL     DEFAULT 'N',
    `audio_use_cnt`           INT       NULL     DEFAULT '0',
    `video_use_cnt`           INT       NULL     DEFAULT '0',
    `key_id`                  INT       NULL     DEFAULT NULL,
    `last_user_yn`            CHAR(1)       NULL     DEFAULT '',
    `last_type`               VARCHAR(10)   NULL     DEFAULT '',
    `last_send_receive`       CHAR(3)       NULL     DEFAULT 'S' COMMENT 'S-발신 R-수신',
    `last_content`            VARCHAR(5000) NULL     DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    UNIQUE INDEX `seq` (`seq`) USING BTREE,
    INDEX `room_id` (`room_id`) USING BTREE,
    INDEX `room_start_time` (`room_start_time`) USING BTREE,
    INDEX `room_status` (`room_status`) USING BTREE,
    INDEX `userid` (`userid`) USING BTREE,
    INDEX `company_id` (`company_id`) USING BTREE,
    INDEX `sender_key` (`sender_key`) USING BTREE,
    INDEX `user_key` (`user_key`) USING BTREE
) AUTO_INCREMENT = 37
;

#################    PDS    #################
CREATE TABLE IF NOT EXISTS `PDS`.`execute_pds_custom_info`
(
    `seq`           INT      NOT NULL AUTO_INCREMENT,
    `custom_id`     VARCHAR(100) NULL     DEFAULT '',
    `execute_id`    VARCHAR(50)  NOT NULL DEFAULT '',
    `pds_group_id`  INT      NOT NULL DEFAULT '0',
    `number_field`  VARCHAR(20)  NULL     DEFAULT '',
    `field_seq`     TINYINT   NULL     DEFAULT '0',
    `custom_number` VARCHAR(15)  NULL     DEFAULT '',
    `rid`           VARCHAR(15)  NULL     DEFAULT '',
    `status`        CHAR(1)      NULL     DEFAULT '',
    `tts_data`      VARCHAR(500) NULL     DEFAULT '',
    `click_key`     VARCHAR(100) NULL     DEFAULT '',
    `hangup_cause`  VARCHAR(50)  NULL     DEFAULT '',
    `hangup_msg`    VARCHAR(50)  NULL     DEFAULT '',
    `hangup_time`   DATETIME     NOT NULL DEFAULT '2010-01-01 00:00:00',
    `read_status`   CHAR(1)      NULL     DEFAULT '',
    `company_id`    VARCHAR(30)  NULL     DEFAULT '',
    `user_data1`    VARCHAR(50)  NULL     DEFAULT '',
    `user_data2`    VARCHAR(50)  NULL     DEFAULT '',
    `user_data3`    VARCHAR(50)  NULL     DEFAULT '',
    PRIMARY KEY (`seq`) USING BTREE,
    INDEX `click_key` (`click_key`) USING BTREE,
    INDEX `company_id` (`company_id`) USING BTREE,
    INDEX `custom_id` (`custom_id`) USING BTREE,
    INDEX `field_seq` (`field_seq`) USING BTREE,
    INDEX `pds_group_id` (`pds_group_id`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `PDS`.`pds_custom_info`
(
    `PDS_SYS_CUSTOM_ID`          VARCHAR(100)  NOT NULL DEFAULT '',
    `PDS_SYS_UPLOAD_DATE`        DATETIME      NULL     DEFAULT '2010-01-01 00:00:00',
    `PDS_SYS_UPDATE_DATE`        DATETIME      NULL     DEFAULT '2010-01-01 00:00:00',
    `PDS_SYS_GROUP_ID`           INT       NOT NULL DEFAULT '0',
    `PDS_SYS_GROUP_TYPE`         INT       NOT NULL DEFAULT '0',
    `PDS_SYS_RESULT_TYPE`        INT       NOT NULL DEFAULT '0',
    `PDS_SYS_DAMDANG_ID`         VARCHAR(20)   NOT NULL DEFAULT '',
    `PDS_SYS_RID_NUMBER`         VARCHAR(20)   NOT NULL DEFAULT '',
    `PDS_SYS_LAST_RESULT_ID`     INT       NULL     DEFAULT '0',
    `PDS_SYS_LAST_RESULT_DATE`   DATETIME      NULL     DEFAULT '2010-01-01 00:00:00',
    `PDS_SYS_LAST_CALL_DATE`     DATETIME      NULL     DEFAULT '2010-01-01 00:00:00',
    `PDS_SYS_LAST_HANGUP_CAUSE`  VARCHAR(30)   NULL     DEFAULT '',
    `PDS_SYS_LAST_CALL_UNIQUEID` VARCHAR(50)   NULL     DEFAULT '',
    `PDS_SYS_COMPANY_ID`         VARCHAR(50)   NOT NULL DEFAULT '',
    `PDS_DATE_1`                 DATE          NULL     DEFAULT '2010-01-01',
    `PDS_DATE_2`                 DATE          NULL     DEFAULT '2010-01-01',
    `PDS_DATE_3`                 DATE          NULL     DEFAULT '2010-01-01',
    `PDS_DAY_1`                  DATE          NULL     DEFAULT '2010-01-01',
    `PDS_DAY_2`                  DATE          NULL     DEFAULT '2010-01-01',
    `PDS_DAY_3`                  DATE          NULL     DEFAULT '2010-01-01',
    `PDS_DATETIME_1`             DATETIME      NULL     DEFAULT '2010-01-01 00:00:00',
    `PDS_DATETIME_2`             DATETIME      NULL     DEFAULT '2010-01-01 00:00:00',
    `PDS_DATETIME_3`             DATETIME      NULL     DEFAULT '2010-01-01 00:00:00',
    `PDS_INT_1`                  INT       NULL     DEFAULT '0',
    `PDS_INT_2`                  INT       NULL     DEFAULT '0',
    `PDS_INT_3`                  INT       NULL     DEFAULT '0',
    `PDS_INT_4`                  INT       NULL     DEFAULT '0',
    `PDS_INT_5`                  INT       NULL     DEFAULT '0',
    `PDS_NUMBER_1`               VARCHAR(15)   NULL     DEFAULT '',
    `PDS_NUMBER_2`               VARCHAR(15)   NULL     DEFAULT '',
    `PDS_NUMBER_3`               VARCHAR(15)   NULL     DEFAULT '',
    `PDS_NUMBER_4`               VARCHAR(15)   NULL     DEFAULT '',
    `PDS_NUMBER_5`               VARCHAR(15)   NULL     DEFAULT '',
    `PDS_STRING_1`               VARCHAR(1000) NULL     DEFAULT '',
    `PDS_STRING_2`               VARCHAR(1000) NULL     DEFAULT '',
    `PDS_STRING_3`               VARCHAR(1000) NULL     DEFAULT '',
    `PDS_STRING_4`               VARCHAR(1000) NULL     DEFAULT '',
    `PDS_STRING_5`               VARCHAR(1000) NULL     DEFAULT '',
    `PDS_STRING_6`               VARCHAR(1000) NULL     DEFAULT '',
    `PDS_STRING_7`               VARCHAR(1000) NULL     DEFAULT '',
    `PDS_STRING_8`               VARCHAR(1000) NULL     DEFAULT '',
    `PDS_STRING_9`               VARCHAR(1000) NULL     DEFAULT '',
    `PDS_STRING_10`              VARCHAR(1000) NULL     DEFAULT '',
    `PDS_STRING_11`              VARCHAR(1000) NULL     DEFAULT '',
    `PDS_STRING_12`              VARCHAR(1000) NULL     DEFAULT '',
    `PDS_STRING_13`              VARCHAR(1000) NULL     DEFAULT '',
    `PDS_STRING_14`              VARCHAR(1000) NULL     DEFAULT '',
    `PDS_STRING_15`              VARCHAR(1000) NULL     DEFAULT '',
    `PDS_STRING_16`              VARCHAR(1000) NULL     DEFAULT '',
    `PDS_STRING_17`              VARCHAR(1000) NULL     DEFAULT '',
    `PDS_STRING_18`              VARCHAR(1000) NULL     DEFAULT '',
    `PDS_STRING_19`              VARCHAR(1000) NULL     DEFAULT '',
    `PDS_STRING_20`              VARCHAR(1000) NULL     DEFAULT '',
    `PDS_CODE_1`                 VARCHAR(50)   NULL     DEFAULT '',
    `PDS_CODE_2`                 VARCHAR(50)   NULL     DEFAULT '',
    `PDS_CODE_3`                 VARCHAR(50)   NULL     DEFAULT '',
    `PDS_CODE_4`                 VARCHAR(50)   NULL     DEFAULT '',
    `PDS_CODE_5`                 VARCHAR(50)   NULL     DEFAULT '',
    `PDS_CODE_6`                 VARCHAR(50)   NULL     DEFAULT '',
    `PDS_CODE_7`                 VARCHAR(50)   NULL     DEFAULT '',
    `PDS_CODE_8`                 VARCHAR(50)   NULL     DEFAULT '',
    `PDS_CODE_9`                 VARCHAR(50)   NULL     DEFAULT '',
    `PDS_CODE_10`                VARCHAR(50)   NULL     DEFAULT '',
    `PDS_MULTICODE_1`            VARCHAR(100)  NULL     DEFAULT '',
    `PDS_MULTICODE_2`            VARCHAR(100)  NULL     DEFAULT '',
    `PDS_MULTICODE_3`            VARCHAR(100)  NULL     DEFAULT '',
    `PDS_CONCODE_1`              VARCHAR(100)  NULL     DEFAULT '',
    `PDS_CONCODE_2`              VARCHAR(100)  NULL     DEFAULT '',
    `PDS_CONCODE_3`              VARCHAR(100)  NULL     DEFAULT '',
    `PDS_CSCODE_1`               VARCHAR(100)  NULL     DEFAULT '',
    `PDS_CSCODE_2`               VARCHAR(100)  NULL     DEFAULT '',
    `PDS_CSCODE_3`               VARCHAR(100)  NULL     DEFAULT '',
    PRIMARY KEY (`PDS_SYS_CUSTOM_ID`) USING BTREE,
    INDEX `PDS_SYS_GROUP_ID` (`PDS_SYS_GROUP_ID`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `PDS`.`pds_research_result`
(
    `seq`           INT      NOT NULL AUTO_INCREMENT,
    `result_date`   DATETIME     NOT NULL DEFAULT '2010-01-01 00:00:00',
    `uniqueid`      VARCHAR(50)  NOT NULL DEFAULT '',
    `hangup_cause`  VARCHAR(50)  NULL     DEFAULT '',
    `hangup_msg`    VARCHAR(100) NULL     DEFAULT '',
    `billsec`       INT      NULL     DEFAULT '0',
    `custom_id`     VARCHAR(50)  NOT NULL DEFAULT '',
    `click_key`     VARCHAR(100) NULL     DEFAULT '',
    `custom_number` VARCHAR(50)  NOT NULL DEFAULT '',
    `execute_id`    VARCHAR(50)  NULL     DEFAULT '',
    `group_id`      INT      NULL     DEFAULT '0',
    `userid`        VARCHAR(30)  NULL     DEFAULT '',
    `research_id`   INT      NULL     DEFAULT '0',
    `tree_path`     VARCHAR(800) NULL     DEFAULT '',
    `my_path_1`     VARCHAR(20)  NULL     DEFAULT '',
    `my_path_2`     VARCHAR(20)  NULL     DEFAULT '',
    `my_path_3`     VARCHAR(20)  NULL     DEFAULT '',
    `my_path_4`     VARCHAR(20)  NULL     DEFAULT '',
    `my_path_5`     VARCHAR(20)  NULL     DEFAULT '',
    `my_path_6`     VARCHAR(20)  NULL     DEFAULT '',
    `my_path_7`     VARCHAR(20)  NULL     DEFAULT '',
    `my_path_8`     VARCHAR(20)  NULL     DEFAULT '',
    `my_path_9`     VARCHAR(20)  NULL     DEFAULT '',
    `my_path_10`    VARCHAR(20)  NULL     DEFAULT '',
    `my_path_11`    VARCHAR(20)  NULL     DEFAULT '',
    `my_path_12`    VARCHAR(20)  NULL     DEFAULT '',
    `my_path_13`    VARCHAR(20)  NULL     DEFAULT '',
    `my_path_14`    VARCHAR(20)  NULL     DEFAULT '',
    `my_path_15`    VARCHAR(20)  NULL     DEFAULT '',
    `my_path_16`    VARCHAR(20)  NULL     DEFAULT '',
    `my_path_17`    VARCHAR(20)  NULL     DEFAULT '',
    `my_path_18`    VARCHAR(20)  NULL     DEFAULT '',
    `my_path_19`    VARCHAR(20)  NULL     DEFAULT '',
    `my_path_20`    VARCHAR(20)  NULL     DEFAULT '',
    `company_id`    VARCHAR(30)  NOT NULL DEFAULT '',
    PRIMARY KEY (`seq`) USING BTREE,
    INDEX `research_id` (`research_id`) USING BTREE,
    INDEX `my_path_1` (`my_path_1`) USING BTREE,
    INDEX `my_path_2` (`my_path_2`) USING BTREE,
    INDEX `my_path_3` (`my_path_3`) USING BTREE,
    INDEX `my_path_4` (`my_path_4`) USING BTREE,
    INDEX `my_path_5` (`my_path_5`) USING BTREE,
    INDEX `my_path_6` (`my_path_6`) USING BTREE,
    INDEX `my_path_7` (`my_path_7`) USING BTREE,
    INDEX `my_path_8` (`my_path_8`) USING BTREE,
    INDEX `my_path_9` (`my_path_9`) USING BTREE,
    INDEX `my_path_10` (`my_path_10`) USING BTREE,
    INDEX `my_path_11` (`my_path_11`) USING BTREE,
    INDEX `my_path_12` (`my_path_12`) USING BTREE,
    INDEX `my_path_13` (`my_path_13`) USING BTREE,
    INDEX `my_path_14` (`my_path_14`) USING BTREE,
    INDEX `my_path_15` (`my_path_15`) USING BTREE,
    INDEX `my_path_16` (`my_path_16`) USING BTREE,
    INDEX `my_path_17` (`my_path_17`) USING BTREE,
    INDEX `my_path_18` (`my_path_18`) USING BTREE,
    INDEX `my_path_19` (`my_path_19`) USING BTREE,
    INDEX `my_path_20` (`my_path_20`) USING BTREE,
    INDEX `company_id` (`company_id`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `PDS`.`result_custom_info`
(
    `seq`            INT          NOT NULL AUTO_INCREMENT,
    `company_id`     VARCHAR(30)      NOT NULL DEFAULT '',
    `result_date`    DATETIME         NOT NULL DEFAULT '2010-01-01 00:00:00',
    `update_date`    DATETIME         NOT NULL DEFAULT '2010-01-01 00:00:00',
    `uniqueid`       VARCHAR(50)      NULL     DEFAULT '',
    `hangup_cause`   VARCHAR(50)      NULL     DEFAULT '',
    `hangup_msg`     VARCHAR(100)     NULL     DEFAULT '',
    `billsec`        INT          NULL     DEFAULT '0',
    `custom_id`      VARCHAR(50)      NULL     DEFAULT '',
    `click_key`      VARCHAR(50)      NULL     DEFAULT '',
    `custom_number`  VARCHAR(50)      NOT NULL DEFAULT '',
    `execute_id`     VARCHAR(50)      NULL     DEFAULT '',
    `group_id`       INT UNSIGNED NULL     DEFAULT '0',
    `userid`         VARCHAR(30)      NULL     DEFAULT '',
    `userid_org`     VARCHAR(30)      NULL     DEFAULT '',
    `userid_tr`      VARCHAR(30)      NULL     DEFAULT '',
    `result_type`    INT          NULL     DEFAULT '0',
    `call_type`      VARCHAR(5)       NULL     DEFAULT '',
    `from_org`       VARCHAR(20)      NULL     DEFAULT '',
    `group_kind`     VARCHAR(10)      NULL     DEFAULT '',
    `group_type`     INT          NULL     DEFAULT '0',
    `RS_DATE_1`      DATE             NULL     DEFAULT '2010-01-01',
    `RS_DATE_2`      DATE             NULL     DEFAULT '2010-01-01',
    `RS_DATE_3`      DATE             NULL     DEFAULT '2010-01-01',
    `RS_DAY_1`       DATE             NULL     DEFAULT '2010-01-01',
    `RS_DAY_2`       DATE             NULL     DEFAULT '2010-01-01',
    `RS_DAY_3`       DATE             NULL     DEFAULT '2010-01-01',
    `RS_DATETIME_1`  DATETIME         NULL     DEFAULT '2010-01-01 00:00:00',
    `RS_DATETIME_2`  DATETIME         NULL     DEFAULT '2010-01-01 00:00:00',
    `RS_DATETIME_3`  DATETIME         NULL     DEFAULT '2010-01-01 00:00:00',
    `RS_INT_1`       INT          NULL     DEFAULT '0',
    `RS_INT_2`       INT          NULL     DEFAULT '0',
    `RS_INT_3`       INT          NULL     DEFAULT '0',
    `RS_INT_4`       INT          NULL     DEFAULT '0',
    `RS_INT_5`       INT          NULL     DEFAULT '0',
    `RS_NUMBER_1`    VARCHAR(15)      NULL     DEFAULT '',
    `RS_NUMBER_2`    VARCHAR(15)      NULL     DEFAULT '',
    `RS_NUMBER_3`    VARCHAR(15)      NULL     DEFAULT '',
    `RS_NUMBER_4`    VARCHAR(15)      NULL     DEFAULT '',
    `RS_NUMBER_5`    VARCHAR(15)      NULL     DEFAULT '',
    `RS_STRING_1`    VARCHAR(1000)    NULL     DEFAULT '',
    `RS_STRING_2`    VARCHAR(1000)    NULL     DEFAULT '',
    `RS_STRING_3`    VARCHAR(1000)    NULL     DEFAULT '',
    `RS_STRING_4`    VARCHAR(1000)    NULL     DEFAULT '',
    `RS_STRING_5`    VARCHAR(1000)    NULL     DEFAULT '',
    `RS_STRING_6`    VARCHAR(1000)    NULL     DEFAULT '',
    `RS_STRING_7`    VARCHAR(1000)    NULL     DEFAULT '',
    `RS_STRING_8`    VARCHAR(1000)    NULL     DEFAULT '',
    `RS_STRING_9`    VARCHAR(1000)    NULL     DEFAULT '',
    `RS_STRING_10`   VARCHAR(500)     NULL     DEFAULT '',
    `RS_STRING_11`   VARCHAR(500)     NULL     DEFAULT '',
    `RS_STRING_12`   VARCHAR(500)     NULL     DEFAULT '',
    `RS_STRING_13`   VARCHAR(500)     NULL     DEFAULT '',
    `RS_STRING_14`   VARCHAR(500)     NULL     DEFAULT '',
    `RS_STRING_15`   VARCHAR(500)     NULL     DEFAULT '',
    `RS_STRING_16`   VARCHAR(500)     NULL     DEFAULT '',
    `RS_STRING_17`   VARCHAR(500)     NULL     DEFAULT '',
    `RS_STRING_18`   VARCHAR(500)     NULL     DEFAULT '',
    `RS_STRING_19`   VARCHAR(500)     NULL     DEFAULT '',
    `RS_STRING_20`   VARCHAR(500)     NULL     DEFAULT '',
    `RS_CODE_1`      VARCHAR(50)      NULL     DEFAULT '',
    `RS_CODE_2`      VARCHAR(50)      NULL     DEFAULT '',
    `RS_CODE_3`      VARCHAR(50)      NULL     DEFAULT '',
    `RS_CODE_4`      VARCHAR(50)      NULL     DEFAULT '',
    `RS_CODE_5`      VARCHAR(50)      NULL     DEFAULT '',
    `RS_CODE_6`      VARCHAR(50)      NULL     DEFAULT '',
    `RS_CODE_7`      VARCHAR(50)      NULL     DEFAULT '',
    `RS_CODE_8`      VARCHAR(50)      NULL     DEFAULT '',
    `RS_CODE_9`      VARCHAR(50)      NULL     DEFAULT '',
    `RS_CODE_10`     VARCHAR(50)      NULL     DEFAULT '',
    `RS_MULTICODE_1` VARCHAR(100)     NULL     DEFAULT '',
    `RS_MULTICODE_2` VARCHAR(100)     NULL     DEFAULT '',
    `RS_MULTICODE_3` VARCHAR(100)     NULL     DEFAULT '',
    `RS_IMG_1`       VARCHAR(100)     NULL     DEFAULT '',
    `RS_IMG_2`       VARCHAR(100)     NULL     DEFAULT '',
    `RS_IMG_3`       VARCHAR(100)     NULL     DEFAULT '',
    `RS_CONCODE_1`   VARCHAR(50)      NULL     DEFAULT '',
    `RS_CONCODE_2`   VARCHAR(50)      NULL     DEFAULT '',
    `RS_CONCODE_3`   VARCHAR(50)      NULL     DEFAULT '',
    `RS_CSCODE_1`    VARCHAR(50)      NULL     DEFAULT '',
    `RS_CSCODE_2`    VARCHAR(50)      NULL     DEFAULT '',
    `RS_CSCODE_3`    VARCHAR(50)      NULL     DEFAULT '',
    PRIMARY KEY (`seq`) USING BTREE,
    INDEX `result_date` (`result_date`) USING BTREE,
    INDEX `uniqueid` (`uniqueid`) USING BTREE,
    INDEX `custom_id` (`custom_id`) USING BTREE,
    INDEX `custom_number` (`custom_number`) USING BTREE,
    INDEX `group_id` (`group_id`) USING BTREE,
    INDEX `userid` (`userid`) USING BTREE,
    INDEX `group_kind` (`group_kind`) USING BTREE,
    INDEX `click_key` (`click_key`) USING BTREE,
    INDEX `userid_tr` (`userid_tr`) USING BTREE
);

#################    STATDB    #################
CREATE TABLE IF NOT EXISTS `STATDB`.`stat_inbound`
(
    `seq`               INT      NOT NULL AUTO_INCREMENT COMMENT '고유키',
    `company_id`        VARCHAR(100) NULL DEFAULT '' COMMENT '회사 ID',
    `group_code`        CHAR(4)      NULL DEFAULT NULL COMMENT '조직코드',
    `group_tree_name`   VARCHAR(50)  NULL DEFAULT '' COMMENT '조직트리명',
    `group_level`       INT      NULL DEFAULT '0' COMMENT '조직레벨',
    `service_number`    VARCHAR(30)  NULL DEFAULT '' COMMENT '대표번호070',
    `hunt_number`       VARCHAR(30)  NULL DEFAULT '' COMMENT '헌트번호',
    `worktime_yn`       CHAR(1)      NULL DEFAULT 'N' COMMENT '업무시간인지 아닌지 스케쥴유형에서 결정됨',
    `category`          VARCHAR(300) NULL DEFAULT '' COMMENT '인입경로',
    `ivr_tree_name`     VARCHAR(300) NULL DEFAULT '' COMMENT 'IVR트리명',
    `dcontext`          VARCHAR(30)  NULL DEFAULT '' COMMENT '다이얼플랜컨텍스트',
    `stat_date`         DATE         NULL DEFAULT '2009-01-01' COMMENT '생성일',
    `stat_hour`         TINYINT   NULL DEFAULT '0' COMMENT '생성시간',
    `total`             INT      NULL DEFAULT '0' COMMENT '총계',
    `onlyread`          INT      NULL DEFAULT '0' COMMENT '단순조회',
    `connreq`           INT      NULL DEFAULT '0' COMMENT '연결요청',
    `success`           INT      NULL DEFAULT '0' COMMENT '응답',
    `callback`          INT      NULL DEFAULT '0' COMMENT '콜백건수',
    `callback_success`  INT      NULL DEFAULT '0' COMMENT '콜백성공건수-콜백이접수된건이지 처리된건은 아님',
    `transfer`          INT      NULL DEFAULT '0' COMMENT '전환한콜수-첫전환콜만',
    `cancel`            INT      NULL DEFAULT '0' COMMENT '포기호',
    `cancel_timeout`    INT      NULL DEFAULT '0' COMMENT '타임아웃포기호-상담사인입X,타임아웃O',
    `cancel_noanswer`   INT      NULL DEFAULT '0' COMMENT '비수신포기호-상담사인입O',
    `cancel_custom`     INT      NULL DEFAULT '0' COMMENT '고객포기호-상담사인입X,타임아웃X',
    `service_level_ok`  INT      NULL DEFAULT '0' COMMENT '서비스레벨안에 전화를 받은건수',
    `billsec_sum`       INT      NULL DEFAULT '0' COMMENT '통화시간',
    `wait_sum`          INT      NULL DEFAULT '0' COMMENT '대기시간합계',
    `billsec_max`       INT      NULL DEFAULT '0' COMMENT '최대통화시간',
    `wait_max`          INT      NULL DEFAULT '0' COMMENT '최대대기시간',
    `wait_cancel_sum`   INT      NULL DEFAULT '0' COMMENT '포기호들의대기시간합계',
    `wait_succ_0_10`    INT      NULL DEFAULT '0' COMMENT '응대호 0초<대기시간=<10초 건수',
    `wait_succ_10_20`   INT      NULL DEFAULT '0' COMMENT '응대호 10초<대기시간<=20초 건수',
    `wait_succ_20_30`   INT      NULL DEFAULT '0' COMMENT '응대호 20초<대기시간<=30초 건수',
    `wait_succ_30_40`   INT      NULL DEFAULT '0' COMMENT '응대호 30초<대기시간<=40초 건수',
    `wait_succ_40`      INT      NULL DEFAULT '0' COMMENT '응대호 40초<대기시간 건수',
    `wait_cancel_0_10`  INT      NULL DEFAULT '0' COMMENT '포기호 0초<대기시간=<10초 건수',
    `wait_cancel_10_20` INT      NULL DEFAULT '0' COMMENT '포기호 10초<대기시간<=20초 건수',
    `wait_cancel_20_30` INT      NULL DEFAULT '0' COMMENT '포기호 20초<대기시간<=30초 건수',
    `wait_cancel_30_40` INT      NULL DEFAULT '0' COMMENT '포기호 30초<대기시간<=40초 건수',
    `wait_cancel_40`    INT      NULL DEFAULT '0' COMMENT '포기호 40초<대기시간 건수',
    PRIMARY KEY (`seq`) USING BTREE,
    INDEX `stat_date` (`stat_date`) USING BTREE,
    INDEX `stat_hour` (`stat_hour`) USING BTREE,
    INDEX `company_id` (`company_id`) USING BTREE,
    INDEX `group_code` (`group_code`) USING BTREE,
    INDEX `group_tree_name` (`group_tree_name`) USING BTREE,
    INDEX `group_level` (`group_level`) USING BTREE,
    INDEX `service_number` (`service_number`) USING BTREE,
    INDEX `worktime_yn` (`worktime_yn`) USING BTREE,
    INDEX `dcontext` (`dcontext`) USING BTREE,
    INDEX `category` (`category`) USING BTREE,
    INDEX `ivr_tree_name` (`ivr_tree_name`) USING BTREE,
    INDEX `hunt_number` (`hunt_number`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `STATDB`.`stat_member_status`
(
    `seq`        INT      NOT NULL AUTO_INCREMENT COMMENT '번호',
    `stat_date`  DATE         NULL DEFAULT '2009-01-01' COMMENT '날짜',
    `stat_hour`  TINYINT   NULL DEFAULT '0' COMMENT '시간',
    `status`     CHAR(1)      NULL DEFAULT '' COMMENT '상태',
    `in_out`     CHAR(1)      NULL DEFAULT 'I' COMMENT 'status가 1일때만 의미가 있음',
    `total`      INT      NULL DEFAULT '0' COMMENT '횟수',
    `diff_sum`   INT      NULL DEFAULT '0' COMMENT '시간',
    `userid`     VARCHAR(30)  NULL DEFAULT '' COMMENT '상담원아이디',
    `company_id` VARCHAR(100) NULL DEFAULT '' COMMENT '회사아이디',
    PRIMARY KEY (`seq`) USING BTREE,
    INDEX `company_id` (`company_id`) USING BTREE,
    INDEX `stat_date` (`stat_date`) USING BTREE,
    INDEX `stat_hour` (`stat_hour`) USING BTREE,
    INDEX `userid` (`userid`) USING BTREE,
    INDEX `in_out` (`in_out`) USING BTREE
) COMMENT ='상담원의 상태 통계';

CREATE TABLE IF NOT EXISTS `STATDB`.`stat_message`
(
    `stat_date`     DATE        NOT NULL DEFAULT '2009-01-01',
    `stat_hour`     TINYINT  NOT NULL DEFAULT '0',
    `service`       VARCHAR(10) NOT NULL DEFAULT '' COMMENT 'SMS,MMS,LMS,KAKAO,RCS',
    `project_id`    VARCHAR(50) NOT NULL DEFAULT '' COMMENT '메세지허브프로젝트아이디',
    `api_key`       VARCHAR(50) NOT NULL DEFAULT '' COMMENT '메세지허브프로젝트API키',
    `userid`        VARCHAR(50) NOT NULL DEFAULT '' COMMENT '사용자아이디',
    `res_code`      VARCHAR(10) NOT NULL DEFAULT '' COMMENT '결과코드',
    `res_data_code` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '메세지발송코드',
    `total`         INT     NOT NULL DEFAULT '0',
    PRIMARY KEY (`stat_date`, `stat_hour`, `service`, `project_id`, `api_key`, `userid`, `res_code`,
                 `res_data_code`) USING BTREE,
    INDEX `stat_date` (`stat_date`) USING BTREE,
    INDEX `stat_hour` (`stat_hour`) USING BTREE,
    INDEX `project_id` (`project_id`) USING BTREE,
    INDEX `userid` (`userid`) USING BTREE,
    INDEX `res_code` (`res_code`) USING BTREE,
    INDEX `res_data_code` (`res_data_code`) USING BTREE,
    INDEX `service` (`service`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `STATDB`.`stat_outbound`
(
    `seq`             INT      NOT NULL AUTO_INCREMENT COMMENT '고유키',
    `company_id`      VARCHAR(100) NULL DEFAULT '' COMMENT '회사아이디',
    `group_code`      CHAR(4)      NULL DEFAULT NULL COMMENT '조직코드',
    `group_tree_name` VARCHAR(50)  NULL DEFAULT '' COMMENT '조직트리명',
    `group_level`     INT      NULL DEFAULT '0' COMMENT '조직레벨',
    `from_org`        VARCHAR(30)  NULL DEFAULT '' COMMENT '일반콜-NOR, 콜백콜-CALLBACK,예약콜-RESERVE, PDS콜-PDS, 고객DB-MAINDB',
    `worktime_yn`     CHAR(1)      NULL DEFAULT 'Y' COMMENT '업무시간여부',
    `dcontext`        VARCHAR(30)  NULL DEFAULT '' COMMENT '다이얼플랜컨텍스트',
    `stat_date`       DATE         NULL DEFAULT '2009-01-01' COMMENT '생성일',
    `stat_hour`       TINYINT   NULL DEFAULT '0' COMMENT '생성시간',
    `total`           INT      NULL DEFAULT '0' COMMENT '총계',
    `success`         INT      NULL DEFAULT '0' COMMENT '응답',
    `billsec_sum`     INT      NULL DEFAULT '0' COMMENT '통화시간합계',
    `wait_sum`        INT      NULL DEFAULT '0' COMMENT '통화전대기시간합계',
    PRIMARY KEY (`seq`) USING BTREE,
    INDEX `company_id` (`company_id`) USING BTREE,
    INDEX `group_code` (`group_code`) USING BTREE,
    INDEX `group_tree_name` (`group_tree_name`) USING BTREE,
    INDEX `group_level` (`group_level`) USING BTREE,
    INDEX `dcontext` (`dcontext`) USING BTREE,
    INDEX `from_org` (`from_org`) USING BTREE,
    INDEX `worktime_yn` (`worktime_yn`) USING BTREE,
    INDEX `stat_date` (`stat_date`) USING BTREE,
    INDEX `stat_hour` (`stat_hour`) USING BTREE
) COMMENT ='OUTBOUND 통계 테이블';

CREATE TABLE IF NOT EXISTS `STATDB`.`stat_queue_wait`
(
    `seq`             INT      NOT NULL AUTO_INCREMENT COMMENT '고유키',
    `company_id`      VARCHAR(100) NULL DEFAULT '' COMMENT '회사 ID',
    `group_code`      CHAR(4)      NULL DEFAULT NULL COMMENT '조직코드',
    `group_tree_name` VARCHAR(50)  NULL DEFAULT '' COMMENT '조직트리명',
    `group_level`     INT      NULL DEFAULT '0' COMMENT '조직레벨',
    `queue_name`      VARCHAR(128) NULL DEFAULT '' COMMENT 'QUEUE 이름',
    `stat_date`       DATE         NULL DEFAULT '2009-01-01' COMMENT '생성일',
    `stat_hour`       TINYINT   NULL DEFAULT '0' COMMENT '생성시간',
    `total_wait`      INT      NULL DEFAULT '0' COMMENT '시간당대기자수합계',
    `max_wait`        INT      NULL DEFAULT '0' COMMENT '최대대기자수',
    PRIMARY KEY (`seq`) USING BTREE,
    INDEX `stat_date` (`stat_date`) USING BTREE,
    INDEX `company_id` (`company_id`) USING BTREE,
    INDEX `group_code` (`group_code`) USING BTREE,
    INDEX `group_tree_name` (`group_tree_name`) USING BTREE,
    INDEX `group_level` (`group_level`) USING BTREE,
    INDEX `queue_name` (`queue_name`) USING BTREE,
    INDEX `stat_hour` (`stat_hour`) USING BTREE
) COMMENT ='헌트대기자수통계 테이블';

CREATE TABLE IF NOT EXISTS `STATDB`.`stat_user_inbound`
(
    `seq`              INT      NOT NULL AUTO_INCREMENT COMMENT '번호',
    `company_id`       VARCHAR(100) NULL DEFAULT '' COMMENT '회사아이디',
    `group_code`       CHAR(4)      NULL DEFAULT NULL COMMENT ' ex>0001',
    `group_tree_name`  VARCHAR(50)  NULL DEFAULT '' COMMENT 'ex>0003_0008_0001',
    `group_level`      INT      NULL DEFAULT '0' COMMENT '3',
    `userid`           VARCHAR(30)  NULL DEFAULT '' COMMENT '상담원아이디',
    `user_stat_yn`     CHAR(1)      NULL DEFAULT 'Y' COMMENT '상담원통계라이센스여부',
    `service_number`   VARCHAR(30)  NULL DEFAULT '' COMMENT '대표번호070',
    `hunt_number`      VARCHAR(30)  NULL DEFAULT '' COMMENT '헌트번호',
    `worktime_yn`      CHAR(1)      NULL DEFAULT '' COMMENT '업무시간여부',
    `category`         VARCHAR(300) NULL DEFAULT '' COMMENT '인입경로',
    `dcontext`         VARCHAR(30)  NULL DEFAULT '' COMMENT '다이얼플랜컨택스트',
    `stat_date`        DATE         NULL DEFAULT '2009-01-01' COMMENT '날짜',
    `stat_hour`        TINYINT   NULL DEFAULT '0' COMMENT '시간',
    `in_total`         INT      NULL DEFAULT '0' COMMENT '총계',
    `in_success`       INT      NULL DEFAULT '0' COMMENT '응답',
    `in_hunt_noanswer` INT      NULL DEFAULT '0' COMMENT '헌트시비응답',
    `in_billsec_sum`   INT      NULL DEFAULT '0' COMMENT '통화시간',
    `in_waitsec_sum`   INT      NULL DEFAULT '0' COMMENT '대기시간',
    `transferer`       INT      NULL DEFAULT '0' COMMENT '전환한콜수',
    `transferee`       INT      NULL DEFAULT '0' COMMENT '전환받은콜수',
    `transferee_succ`  INT      NULL DEFAULT '0' COMMENT '전환받은성공콜수',
    `callback_dist`    INT      NULL DEFAULT '0' COMMENT '콜백분배받은건수',
    `callback_succ`    INT      NULL DEFAULT '0' COMMENT '분배받은 콜백을 처리한건수',
    `service_level_ok` INT      NULL DEFAULT '0' COMMENT '서비스레벨안에 전화를 받은건수',
    PRIMARY KEY (`seq`) USING BTREE,
    INDEX `company_id` (`company_id`) USING BTREE,
    INDEX `group_code` (`group_code`) USING BTREE,
    INDEX `group_tree_name` (`group_tree_name`) USING BTREE,
    INDEX `group_level` (`group_level`) USING BTREE,
    INDEX `userid` (`userid`) USING BTREE,
    INDEX `service_number` (`service_number`) USING BTREE,
    INDEX `hunt_number` (`hunt_number`) USING BTREE,
    INDEX `worktime_yn` (`worktime_yn`) USING BTREE,
    INDEX `stat_date` (`stat_date`) USING BTREE,
    INDEX `stat_hour` (`stat_hour`) USING BTREE,
    INDEX `user_stat_yn` (`user_stat_yn`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `STATDB`.`stat_user_outbound`
(
    `seq`                INT      NOT NULL AUTO_INCREMENT,
    `company_id`         VARCHAR(100) NOT NULL DEFAULT '',
    `group_code`         CHAR(4)      NULL     DEFAULT NULL COMMENT '조직코드',
    `group_tree_name`    VARCHAR(50)  NULL     DEFAULT '' COMMENT '조직트리명',
    `group_level`        INT      NULL     DEFAULT '0' COMMENT '조직트리레벨',
    `cid_number`         VARCHAR(30)  NULL     DEFAULT '' COMMENT '발신번호',
    `userid`             VARCHAR(30)  NOT NULL DEFAULT '',
    `user_stat_yn`       CHAR(1)      NULL     DEFAULT 'Y',
    `from_org`           VARCHAR(30)  NULL     DEFAULT '' COMMENT '일반콜-NOR, 콜백콜-CALLBACK,예약콜-RESERVE, PDS콜-PDS, 고객DB-MAINDB',
    `worktime_yn`        CHAR(1)      NULL     DEFAULT 'Y' COMMENT '업무시간여부',
    `dcontext`           VARCHAR(30)  NULL     DEFAULT '' COMMENT '다이얼플랜컨텍스트',
    `stat_date`          DATE         NULL     DEFAULT '2009-01-01',
    `stat_hour`          TINYINT   NULL     DEFAULT '0',
    `out_total`          INT      NULL     DEFAULT '0',
    `out_success`        INT      NULL     DEFAULT '0',
    `out_billsec_sum`    INT      NULL     DEFAULT '0',
    `callback_call_cnt`  INT      NULL     DEFAULT '0',
    `callback_call_succ` INT      NULL     DEFAULT '0',
    `reserve_call_cnt`   INT      NULL     DEFAULT '0',
    `reserve_call_succ`  INT      NULL     DEFAULT '0',
    PRIMARY KEY (`seq`) USING BTREE,
    INDEX `company_id` (`company_id`) USING BTREE,
    INDEX `group_code` (`group_code`) USING BTREE,
    INDEX `group_tree_name` (`group_tree_name`) USING BTREE,
    INDEX `group_level` (`group_level`) USING BTREE,
    INDEX `dcontext` (`dcontext`) USING BTREE,
    INDEX `from_org` (`from_org`) USING BTREE,
    INDEX `worktime_yn` (`worktime_yn`) USING BTREE,
    INDEX `userid` (`userid`) USING BTREE,
    INDEX `stat_date` (`stat_date`) USING BTREE,
    INDEX `stat_hour` (`stat_hour`) USING BTREE,
    INDEX `cid_number` (`cid_number`) USING BTREE
);

CREATE TABLE IF NOT EXISTS `STATDB`.`stat_user_ranking`
(
    `seq`               INT      NOT NULL AUTO_INCREMENT COMMENT '고유키',
    `company_id`        VARCHAR(100) NULL DEFAULT '' COMMENT '회사 ID',
    `group_code`        CHAR(4)      NULL DEFAULT NULL COMMENT '조직코드',
    `group_tree_name`   VARCHAR(50)  NULL DEFAULT '' COMMENT '조직트리명',
    `group_level`       INT      NULL DEFAULT '0' COMMENT '조직레벨',
    `userid`            VARCHAR(30)  NULL DEFAULT '' COMMENT '상담원아이디',
    `worktime_yn`       CHAR(1)      NULL DEFAULT 'Y' COMMENT '업무시간여부',
    `stat_date`         DATE         NULL DEFAULT '2009-01-01' COMMENT '생성일',
    `total_success`     INT      NULL DEFAULT '0' COMMENT '통화성공총계',
    `in_success`        INT      NULL DEFAULT '0' COMMENT '인바운드성공',
    `out_success`       INT      NULL DEFAULT '0' COMMENT '아웃바운드성공',
    `total_billsec_sum` INT      NULL DEFAULT '0' COMMENT '통화성공통화시간총계',
    `in_billsec_sum`    INT      NULL DEFAULT '0' COMMENT '인바운드성공통화시간',
    `out_billsec_sum`   INT      NULL DEFAULT '0' COMMENT '아웃바운드성공통화시간',
    `callback_success`  INT      NULL DEFAULT '0' COMMENT '콜백처리성공',
    PRIMARY KEY (`seq`) USING BTREE,
    INDEX `stat_date` (`stat_date`) USING BTREE,
    INDEX `company_id` (`company_id`) USING BTREE,
    INDEX `group_code` (`group_code`) USING BTREE,
    INDEX `group_tree_name` (`group_tree_name`) USING BTREE,
    INDEX `group_level` (`group_level`) USING BTREE,
    INDEX `userid` (`userid`) USING BTREE,
    INDEX `worktime_yn` (`worktime_yn`) USING BTREE
) COMMENT ='상담원별랭킹 테이블';

CREATE TABLE IF NOT EXISTS `STATDB`.`stat_voc`
(
    `seq`                INT      NOT NULL AUTO_INCREMENT COMMENT '고유키',
    `company_id`         VARCHAR(100) NOT NULL DEFAULT '' COMMENT '회사 ID',
    `voc_group_id`       INT      NULL     DEFAULT '0',
    `research_id`        INT      NULL     DEFAULT '0' COMMENT '설문아이디',
    `userid`             VARCHAR(30)  NULL     DEFAULT '' COMMENT '상담원아이디',
    `research_tree_path` VARCHAR(800) NULL     DEFAULT '' COMMENT '설문단계',
    `research_response`  VARCHAR(20)  NULL     DEFAULT '' COMMENT '설문답변',
    `stat_date`          DATE         NOT NULL DEFAULT '2009-01-01' COMMENT '생성일',
    `stat_hour`          TINYINT   NOT NULL DEFAULT '0' COMMENT '생성시간',
    `total`              INT      NOT NULL DEFAULT '0' COMMENT '총계',
    PRIMARY KEY (`seq`) USING BTREE,
    INDEX `stat_date` (`stat_date`) USING BTREE,
    INDEX `stat_hour` (`stat_hour`) USING BTREE,
    INDEX `company_id` (`company_id`) USING BTREE,
    INDEX `research_id` (`research_id`) USING BTREE,
    INDEX `userid` (`userid`) USING BTREE,
    INDEX `research_tree_path` (`research_tree_path`(333)) USING BTREE
) COMMENT ='VOC 통계 테이블';

CREATE TABLE IF NOT EXISTS `STATDB`.`stat_wtalk`
(
    `seq`             INT      NOT NULL AUTO_INCREMENT,
    `company_id`      VARCHAR(50)  NULL     DEFAULT '' COMMENT '회사아이디',
    `channel_type`    VARCHAR(10)  NULL     DEFAULT '' COMMENT '채널타입',
    `sender_key`      VARCHAR(100) NULL     DEFAULT '' COMMENT '상담톡카카오가입서비스아이디',
    `userid`          VARCHAR(50)  NULL     DEFAULT '' COMMENT '상담원 아이디',
    `group_code`      CHAR(4)      NULL     DEFAULT NULL COMMENT '조직코드',
    `group_tree_name` VARCHAR(50)  NULL     DEFAULT '' COMMENT '조직트리명',
    `group_level`     INT      NULL     DEFAULT '0' COMMENT '조직레벨',
    `worktime_yn`     CHAR(1)      NULL     DEFAULT 'Y',
    `stat_date`       DATE         NOT NULL DEFAULT '2009-01-01',
    `stat_hour`       TINYINT   NOT NULL DEFAULT '0',
    `action_type`     VARCHAR(50)  NULL     DEFAULT '' COMMENT '액션타입',
    `cnt`             INT      NOT NULL DEFAULT '0',
    PRIMARY KEY (`seq`) USING BTREE,
    INDEX `stat_date` (`stat_date`) USING BTREE,
    INDEX `stat_hour` (`stat_hour`) USING BTREE,
    INDEX `group_code` (`group_code`) USING BTREE,
    INDEX `group_tree_name` (`group_tree_name`) USING BTREE,
    INDEX `group_level` (`group_level`) USING BTREE,
    INDEX `worktime_yn` (`worktime_yn`) USING BTREE,
    INDEX `sender_key` (`sender_key`) USING BTREE,
    INDEX `userid` (`userid`) USING BTREE,
    INDEX `action_type` (`action_type`) USING BTREE
);
